opensafely-core/airlock

- justfile
* want to reuse this elsewhere in future
> chore: split out dotenv target in justfile for reuse

- assets/justfile
* default env on MacOS does not support -C
> fix: amend assets justfile for macos compatilibity

- .dockerignore
- .github/workflows/main.yml
- .test.env
- Dockerfile
- docker/.env
- docker/Dockerfile
- docker/dependencies-build.txt
- docker/dependencies.txt
- docker/docker-compose.yml
- docker/entrypoints/dev.sh
- docker/entrypoints/prod.sh
- docker/justfile
- gunicorn.conf.py
- justfile
- pyproject.toml
- requirements.prod.in
- requirements.prod.txt
- tests/functional/test_page.py
- tests/test_python_version.py
* Mostly cribbed from job-server & release-hatch
* skip running the playwright tests in docker (as well as locally) for the time being in order to get something deployed sooner
> feat: import docker build / deployment system

- .github/workflows/main.yml
- docker/justfile
* this exists in job-server, not here!
> fix: bugs in github workflow

- airlock/nav.py
- airlock/settings.py
- airlock/templates/file_browser/index.html
- airlock/templates/requests.html
- airlock/templates/workspaces.html
- airlock/urls.py
- airlock/users.py
- airlock/views.py
- airlock/workspace_api.py
- tests/integration/test_views.py
- tests/unit/test_login_api.py
- tests/unit/test_nav.py
- tests/unit/test_user.py
- tests/unit/test_workspace_api.py
- Add list pages for Workspaces and Requests
- Basic navigation in header to list pages.
- Remove support for navigating from WorkspaceRoot object
> Add list views for workspaces and requests

- airlock/settings.py
- airlock/templates/file_browser/index.html
- airlock/urls.py
- airlock/views.py
- airlock/workspace_api.py
- tests/factories.py
- tests/integration/test_views.py
- tests/unit/test_workspace_api.py
- Improve name of root breadcrumb, and link it
- Add add file machinery to workspace_api
- Expose UI for adding file to request
> Support adding file to ReleaseRequest

- airlock/services/__init__.py
- airlock/views.py
> Fix missed reactor because to PRs merged in parallel

- airlock/settings.py
- airlock/views.py
Add messages on adding a file, submitted a request for review, rejecting a request, and releasing files
> Add minimal alert messages

- airlock/views.py
so that get_absolute_url works in the template
> Pass a Workspace to the request view

- airlock/api.py
- airlock/forms.py
- airlock/templates/file_browser/index.html
- local_db/api.py
- tests/integration/test_views.py
- tests/unit/test_api.py
For displaying them, I needed to be able to look them up by name.
> Refactor filegroups to be a dict

- airlock/file_browser_api.py
- airlock/templates/file_browser/index.html
- airlock/templates/file_browser/tree.html
- airlock/views.py
- tests/conftest.py
- tests/factories.py
- tests/functional/test_e2e.py
- tests/integration/test_old_api.py
- tests/integration/test_views.py
- tests/unit/test_api.py
- tests/unit/test_file_browser_api.py
- **Make test factories use the api to create requests**
- **Refactor PathItem to support groups.**
> group trees

- airlock/file_browser_api.py
- airlock/templates/file_browser/tree.html
- tests/unit/test_file_browser_api.py
This involved slightly refactoring previoius code to just having an
expanded attribute, set when we build the tree.
> Expand all directories withing a filegroup

- airlock/templates/base.html
- airlock/templates/file_browser/csv.html
- airlock/templates/file_browser/index.html
- airlock/templates/file_browser/tree.html
- airlock/templates/index.html
- airlock/templates/jobserver-error.html
- airlock/templates/login.html
- airlock/templates/requests.html
- airlock/templates/workspaces.html
- justfile
- requirements.dev.in
- requirements.dev.txt
- **Add djhtml template formatter**
- **Run djhtml formatter**
> Add djhtml to format templates

- airlock/templates/file_browser/index.html
> Chrome 108 doesn't support nested css selectors

- airlock/templates/login.html
Fixes #145 
Hides the submit button and shows a spinner when the login form is submitted.
Found a bug (I think) in the components library which the first commit is a workaround for. Job-server [ticket](https://github.com/opensafely-core/job-server/issues/4183) raised.
> Login spinner

- DEVELOPERS.md
I wasn't sure whether Airlock was automatically deployed and this was the first place I thought to look to check the answer. Adding it here in case anyone else has the same question in future.
> Add note on automated deployments

- airlock/business_logic.py
- airlock/views/helpers.py
- airlock/views/request.py
- airlock/views/workspace.py
- local_db/management/commands/backpopulate_file_id.py
- tests/factories.py
- tests/functional/test_e2e.py
- tests/integration/views/test_request.py
- tests/unit/test_business_logic.py
- **Move the permissions checks from validate_workspace into the BLL**
- **Add request permissions check into BLL**
- **Rename validate_foo to get_foo_or_raise**
> permissions checks bll

- airlock/templates/file_browser/csv.html
- airlock/templates/file_browser/index.html
Couple of small changes that make a difference to the render time of large
tables.
> Table render performance tweaks

- airlock/business_logic.py
- airlock/renderers.py
- airlock/views/helpers.py
- airlock/views/request.py
- tests/functional/test_e2e.py
- tests/integration/views/test_helpers.py
- tests/integration/views/test_workspace.py
- tests/unit/test_business_logic.py
- tests/unit/test_file_browser_api.py
- tests/unit/test_renderers.py
- **Refactor the just added rendering framework.**
- **Add immutable cache ids to contents urls**
> Far futures cacheable urls

- airlock/business_logic.py
- airlock/file_browser_api.py
- airlock/forms.py
- airlock/login_api.py
- airlock/middleware.py
- airlock/nav.py
- airlock/renderers.py
- airlock/users.py
- airlock/views/__init__.py
- airlock/views/workspace.py
- justfile
- local_db/data_access.py
- local_db/models.py
- old_api/__init__.py
- old_api/schema.py
- pyproject.toml
- requirements.dev.in
- requirements.dev.txt
- tests/unit/test_business_logic.py
This is very much experimental and subject to review. The aim is to overall improve developer experience by catching more problems that it creates. We expect there to be some short term friction as we collectively get accustomed to mypy and its ways. But if longer term the balance doesn't seem to be paying off then we should be ruthless about ditching it, or relaxing the config.
In particular, Django and its metaclass magic is sometimes an awkward fit here. There are already a couple of places where we just `# type: ignore` the error and we should feel sad but not bad about adding more if we have to.
See also the discussion on an earlier spike of this work in #173
> Add mypy type checking

- airlock/templates/index.html
- airlock/urls.py
- airlock/views/__init__.py
- airlock/views/auth.py
- airlock/views/index.py
- tests/functional/test_e2e.py
- tests/functional/test_home_page.py
- tests/functional/test_login.py
- tests/integration/test_auth_views.py
- tests/integration/views/test_index.py
- tests/integration/views/test_workspace.py
Instead, redirect the workspaces index
> Remove the index page.

- airlock/business_logic.py
- airlock/templates/file_browser/index.html
- tests/factories.py
- tests/functional/test_e2e.py
- tests/integration/views/test_request.py
- tests/unit/test_business_logic.py
> Require two approvals for all output files before releasing

- airlock/forms.py
* fixes https://github.com/opensafely-core/airlock/issues/219
> Don't offer to add a file as withdrawn

- airlock/business_logic.py
- airlock/templates/file_browser/index.html
- airlock/templates/requests_for_workspace.html
- airlock/templates/requests_workspace.html
- airlock/urls.py
- airlock/views/__init__.py
- airlock/views/request.py
- local_db/data_access.py
- tests/integration/views/test_request.py
- tests/unit/test_business_logic.py
* fix https://github.com/opensafely-core/airlock/issues/211
> Add navigation links to other requests for a workspace

- airlock/business_logic.py
- airlock/file_browser_api.py
- airlock/views/helpers.py
- tests/unit/test_file_browser_api.py
- **Refactor file/directory detection**
- **Add missing types to tree functions.**
> Refactor file/directory detection, and improve typing

- airlock/business_logic.py
- tests/unit/test_business_logic.py
> Prevent release of an empty request

- airlock/templates/file_browser/csv.html
Reverts opensafely-core/airlock#273
> Revert "Fix csv column sorting by adding a data-order attribute"

- airlock/templates/file_browser/csv.html
Reverts opensafely-core/airlock#274
> Revert "Revert "Fix csv column sorting by adding a data-order attribute""

- airlock/templates/file_browser/contents.html
- airlock/views/request.py
But only when the request is not in a final state.
> Only the author can edit context/controls fields

- docs/creating-a-release-request.md
- docs/index.md
- docs/reviewing.md
To incorporate feedback from @rose-higgins on the [previous PR](https://github.com/opensafely-core/airlock/pull/241), plus make the chrome warning more visible.
> Updates to wording in docs

- airlock/business_logic.py
- tests/unit/test_business_logic.py
* fixes https://github.com/opensafely-core/airlock/issues/283
> Record C3 in the audit log

- DEVELOPERS.md
- airlock/templates/base.html
- airlock/templates/login.html
- airlock/templates/requests.html
- airlock/templates/workspaces.html
- tests/functional/test_e2e.py
- Fixed wonky account dropdown
- Moved logout button under account dropdown
- Fixed associated tests
---
- Moved text under article header to improve visibility
- This can be tweaked once users have used the system
- Improved form spacing and success button styles
---
- Update card layout and use article header
- Add an empty state
---
- Update card layout and use article header
- Add an empty state
> Update styles for header, login, requests, and workspaces

- airlock/static/assets/activity.js
- airlock/static/assets/datatable.css
- airlock/static/assets/file_browser/csv.js
- airlock/static/assets/file_browser/index.css
- airlock/static/assets/file_browser/index.js
- airlock/static/assets/login.js
- airlock/templates/activity.html
- airlock/templates/file_browser/csv.html
- airlock/templates/file_browser/directory.html
- airlock/templates/file_browser/index.html
- airlock/templates/file_browser/request.html
- airlock/templates/file_browser/workspace.html
- airlock/templates/login.html
- airlock/templates/requests_for_workspace.html
- tests/integration/views/test_request.py
- tests/integration/views/test_workspace.py
- Improve empty states
- Move title and action buttons to content header
- Restyle full width content and use CSS Grid for layout
- Create CSS and JS files for imported assets
- Update description list for requests
- Fix table styling for cards without padding
> Style updates and asset files

- airlock/business_logic.py
- airlock/templates/file_browser/file.html
- airlock/urls.py
- airlock/views/__init__.py
- airlock/views/request.py
- local_db/data_access.py
- tests/functional/test_e2e.py
- tests/integration/views/test_request.py
- tests/unit/test_business_logic.py
* UI buttons could be better, but we can fix that in post 
* fixes https://github.com/opensafely-core/airlock/issues/284
> Support undo for a file review

- airlock/renderers.py
- tests/unit/test_renderers.py
We had one of these in production and it triggered a 500 which then triggered a confusing iframe permissions error.
> Handle empty CSV files

- .github/workflows/main.yml
- tests/factories.py
- **Fix load-example-data**
- **Run load-example-data in CI to detect breakage**
> fix load data

- airlock/business_logic.py
- airlock/file_browser_api.py
- airlock/forms.py
- airlock/templates/add_files.html
- airlock/templates/file_browser/directory.html
- airlock/types.py
- airlock/views/workspace.py
- local_db/data_access.py
- tests/integration/views/test_workspace.py
- **Add workplace status to directory view.**
- **Add group attribute to RequestFile**
- **Add multiselect add files workflow**
Fixes #242
> Support for adding multiple files at once

- local_db/data_access.py
- local_db/models.py
* fixes https://github.com/opensafely-core/airlock/issues/376
> Refactor DAL methods into to_dict()

- airlock/business_logic.py
- airlock/templates/file_browser/file.html
- airlock/views/request.py
- docs/reviewing.md
- tests/integration/views/test_request.py
* https://github.com/opensafely-core/airlock/issues/373
> Reword 'reject' to 'request changes' for files

- DEVELOPERS.md
- docs/request-states.md
- justfile
- scripts/statemachine.py
Integrate with just fix/check like other tools.
> Autogenerate diagram for RequestStatus state machine

- airlock/static/assets/file_browser/index.css
- airlock/static/icons/draft_outline.svg
- airlock/static/icons/keyboard_arrow_right.svg
- airlock/templates/file_browser/tree.html
- Change background colour on selected file/folder
- Reduce horizontal spacing around tree elements
- Add arrows to show dropdown states
- Add colours for supporting and withdraw items
> Improve styles for file tree

- airlock/templates/file_browser/group.html
- tests/functional/test_request_pages.py
Fixes #404 
SHOW_C3 setting now controls only whether comments are visible.
> Reinstate context and controls

- tests/factories.py
- tests/integration/test_settings.py
- tests/integration/views/test_request.py
- tests/integration/views/test_workspace.py
- tests/local_db/test_data_access.py
- tests/test_python_version.py
- tests/unit/test_business_logic.py
- tests/unit/test_file_browser_api.py
- tests/unit/test_notifications.py
Some simple nits from running mypy on `tests/`
Before: 
Found 65 errors in 17 files
After: 
Found 28 errors in 11 files
> Fix some mypy errors from tests/

- airlock/static/assets/datatable.css
- airlock/static/assets/file_browser/tree.css
Replace nested CSS with top-level CSS attributes.
> Remove nested CSS

- docs/creating-a-release-request.md
* these are currently enabled, I think?
> Un-comment context & controls docs

- airlock/static/assets/file_browser/index.css
- airlock/templates/file_browser/file.html
SUPPORTING and WITHDRAWN are file types, not status.
> Use file-type semantic class name, not file-status

- airlock/business_logic.py
- airlock/views/request.py
- tests/factories.py
- tests/unit/test_business_logic.py
- tests/unit/test_file_browser_api.py
> Add file group to file review audit logs

- airlock/business_logic.py
- airlock/file_browser_api.py
- airlock/static/assets/file_browser/tree.css
- airlock/templates/file_browser/index.html
- tests/unit/test_file_browser_api.py
Fixes #489
Agreed reviews: 2 reviewers have approved:
Agreed reviews: 2 reviewers have requested changes:
Conflicted reviews: Current reviewer has approved, other reviewer has requested changes:
Author's view of conflicted file in request:
Author's view of under-review file in workspace (this is unchanged):
Author's view of updated file in workspace (this is unchanged):
After returning and resubmitting (with no changes, so previous request-changes decisions are now undecided) - shows the user review status:
Review has now approved and completed review (other reviewer has rejected and not yet completed):
Other reviewer has now completed, shows combined decision:
> Update css classes for combined file decision status

- airlock/business_logic.py
- tests/unit/test_file_browser_api.py
> Hide decisions if you are an outout-checker and also an author.

- airlock/views/request.py
* this is a bit too noisy
* fixes https://github.com/opensafely-core/airlock/issues/490
> Don't send notification for reviews

- airlock/business_logic.py
- airlock/views/request.py
- tests/factories.py
- tests/functional/test_e2e.py
- tests/integration/views/test_request.py
- tests/unit/test_business_logic.py
* absolute bare minimum to make this correct
* lots of test updates
* fixes #462
> Prevent submitting a release request with empty context & controls

- airlock/templates/_includes/header.html
> Make it clearer that switching users is only available in testing

- airlock/business_logic.py
- tests/functional/test_login.py
- **Factor our output-checker-but-not-author logic**
- **Drive by fix for functional test when there's local env vars**
> Add user_can_review function

- airlock/business_logic.py
- tests/unit/test_business_logic.py
> Comment authors are always allowed to delete their own comments

- airlock/templates/file_browser/directory.html
- airlock/views/code.py
- tests/integration/views/test_code.py
> Hide checkboxes which can't be used

- airlock/templates/file_browser/index.html
> Scroll to window top instead of content in tree

- airlock/business_logic.py
- airlock/forms.py
- airlock/management/commands/audit.py
- airlock/templates/file_browser/group.html
- airlock/templates/file_browser/workspace.html
- airlock/views/request.py
- airlock/views/workspace.py
- local_db/data_access.py
- local_db/migrations/0018_filegroupcomment_visibility.py
- local_db/models.py
- tests/integration/views/test_request.py
- tests/integration/views/test_workspace.py
- tests/local_db/test_data_access.py
- tests/unit/test_business_logic.py
Reverts opensafely-core/airlock#570
> Revert "Filter out audit logs that a user cannot see"

- airlock/views/helpers.py
- airlock/views/request.py
- airlock/views/workspace.py
* following the way it's now done in request.py
* also bump the empty array test into the helper function
* remove the empty test from request.py
> Always show workspaces msgs with the correct level

- justfile
* most of the time I'm working on python & this would give me faster feedback
> Run mypy earlier in `just check`

- airlock/templates/file_browser/contents.html
- airlock/templates/file_browser/file.html
- airlock/templates/file_browser/group.html
- airlock/views/request.py
- tests/functional/test_request_pages.py
- **Refactor request group template context**
- **Add view context modal to contents view**
- **Add small functional test for context modal**
Button here: ![image](https://github.com/user-attachments/assets/c8d964db-18cf-4675-ae71-0f4833680227)
Modal: 
Fixes #483
> Add group context modal to file view

- airlock/business_logic.py
- justfile
- tests/__init__.py
- tests/factories.py
- tests/functional/conftest.py
- tests/integration/management/commands/test_backpopulate_file_manifest_data.py
- tests/integration/views/test_helpers.py
- tests/integration/views/test_request.py
- tests/integration/views/test_workspace.py
- tests/local_db/test_data_access.py
- tests/local_db/test_models.py
- tests/test_tracing.py
- tests/unit/test_business_logic.py
- tests/unit/test_user.py
* fix or ignore all remaining mypy issues with `tests/`
* add `tests/` to the list of directories checked as standard by mypy
* add some type annotations to `test/factories.py` and fix mypy issues as they arise
> Enable mypy for tests/

- .github/workflows/job-server.yml
- .github/workflows/main.yml
- .github/workflows/pages-deployment.yml
- job-server/justfile
- job-server/local-setup.sh
- justfile
- **add new required env var to local job-server configuration**
- **use ubuntu-22.04 in CI, not latest, as that moves under us**
- **Add scheduled CI task to validate local job-server setup**
> update jobserver and cover in ci

- airlock/static/assets/file_browser/tree.css
> Prioritise selected style for items in the tree

- assets/src/styles/main.css
> Style file groups to increase visual prominence

- airlock/nav.py
- airlock/permissions.py
- airlock/templates/requests_for_output_checker.html
- airlock/templates/requests_for_researcher.html
- airlock/urls.py
- airlock/views/__init__.py
- airlock/views/request.py
- tests/functional/test_e2e.py
- tests/integration/views/test_request.py
- tests/unit/test_nav.py
> Create different views for researchers and output checkers

- airlock/management/commands/run_file_uploader.py
Bump the log level so we can tell if the file uploader starts on prod
> Up the log level for file uploader startup

- .github/workflows/update-dependencies.yml
- justfile
First, rename to update-pipeline, so match other repos naming.
Second, ensure that the .txt is updated if the .in has changed
> Fix pipeline updates

- airlock/business_logic.py
- tests/unit/test_business_logic.py
Adds an update along with the APPROVED state change that reports how many files are pending upload
> Include the number of files to be uploaded with Approved notifications

- airlock/templates/file_browser/request/request.html
- airlock/views/request.py
- tests/integration/views/test_request.py
> Add a tooltip to the enabled Reject button

- airlock/models.py
- airlock/templates/requests_for_output_checker.html
- airlock/templates/requests_for_researcher.html
- assets/templates/_components/list-group/list-group-rich-item.html
> Add meta data to requests view

- airlock/templates/workspaces.html
> Enabled drop down toggle on project names

- airlock/views/workspace.py
- tests/functional/test_workspace_pages.py
I've slightly adapted the suggested text here, hopefully for the better!
Closes #795
> Clarify text in tooltip

- airlock/templates/file_browser/request/filegroup.html
- assets/src/styles/main.css
> Make the context/controls modal bigger

- docs/how-tos/create-and-submit-a-release-request.md
> Add a warning to clarify that only one request per workspace is allowed

- airlock/templatetags/airlock.py
- assets/src/scripts/datatable.js
- assets/src/styles/datatable.css
Looks like this:
[Screencast from 07-03-25 08:13:00.webm](https://github.com/user-attachments/assets/c6e17a38-5604-4f8b-94f1-48f9eb43beaa)
> Display a loading indicator while the table is sorting

- airlock/views/request.py
- tests/integration/views/test_request.py
Withdrawing files from a pending request deletes the files. If we withdraw all files from a directory (using the multiselect), we can't redirect back to the directory, because it's no longer a valid url, so we redirect to the group instead. This is consistent with the behaviour when withdrawing a single file from a pending request.
> Redirect to group after deleting all files from a directory

- tests/functional/test_docs_screenshots.py
This point in the test has seen the occasional "db locked" error, which could possibly be due to the htmx polling interfering with the manual bll calls. Calling the run_file_uploader management command makes for simpler code in the test and more closely mimics the way the uploads work.
Tentatively maybe fixes #892
> Use the file uploader in screenshot tests

- dotenv-sample
HTTPS requests will be rejected by docker
> Use correct URL scheme for AIRLOCK_API_ENDPOINT

- tests/functional/test_request_pages.py
This point in the test has seen the occasional "db locked" error, which could possibly be due to the htmx polling interfering with the manual bll calls. Calling the run_file_uploader management command makes for simpler code in the test and more closely mimics the way the uploads work.
(A similar update - in https://github.com/opensafely-core/airlock/pull/900 - was done for the screenshot functional tests; which also encountered the "db locked" error, somewhat more frequently, and haven't (so far) since the change was made)
> Use the file uploader to upload files during functional tests

- airlock/models.py
- tests/functional/test_request_pages.py
- tests/unit/test_models.py
> Show a different decision status to researchers when there are conflicting reviews
