opensafely-core/airlock

- airlock/settings.py
- tests/unit/test_settings.py
Message looks like:
```
RuntimeError: Missing environment variable: DJANGO_DEBUG
If you are running commands locally outside of `just` then you should
make sure that your `.env` file is being loaded into the environment,
which you can do in Bash using:
set -a; source .env; set +a
If you are seeing this error when running via `just` (which should
automatically load variables from `.env`) then you should check that
`.env` contains all the variables listed in `dotenv-sample` (which may
have been updated since `.env` was first created).
If you are seeing this error in production then you haven't configured
things properly.
```
> Add helpful error message for missing env vars

- DEVELOPERS.md
- justfile
And make CI output a bit cleaner.
> Expand DEVELOPERS docs

- airlock/settings.py
- airlock/templates/base.html
- airlock/templates/index.html
- airlock/urls.py
- airlock/views.py
- dotenv-sample
- tests/integration/test_views.py
- tests/unit/test_urls.py
This just adds a single "Hello World" index view. But it gives us something to target as an initial working deployment.
> Minimal deployable application

- tests/conftest.py
Tiny pytest plugin borrowed from ehrQL. This forces us to either deal with or explicitly silence any warnings.
> Fail test run if any warnings present

- .github/workflows/main.yml
- DEVELOPERS.md
- justfile
The major change here is to use positional arguments for argument forwarding so that arguments with spaces are now handled correctly e.g
just test -k 'not functional'
We also slightly tweak the approach to the initial creation of the `.env` file. Rather than always throwing an error on the first run we now assume that `just devenv` will be run as a standalone initial step (both by developers and in CI) and do the necessary set up there without throwing an error.
This allows us to simplify both the Getting Started process and the CI config.
> Further `justfile` improvements

- DEVELOPERS.md
- airlock/settings.py
- airlock/templates/file_browser/index.html
- airlock/urls.py
- airlock/views.py
- airlock/workspace_api.py
- assets/views.py
- dotenv-sample
- justfile
- tests/integration/test_views.py
- tests/unit/test_workspace_api.py
Most of this should be pretty obvious. A few high-level notes:
* You'll see I've used type annotations in a few places, but not consistently. This is a practice we developed in ehrQL where we abandoned the attempt at full type checking (either it wasn't ready for something like ehrQL, or we weren't ready for it), but still found ourselves wanting to mention types in comments where they weren't immediately clear. So we ended up using type annotations as a form of terse, standardised comment. And possibly this will inch us towards a world where we do end up using types for real.
* My "unit" tests touch the filesystem, which will cause the purists to retch in horror. I'm taking the ehrQL stance that "unit test" just means "fast and focused" and not worrying too much about the precise …
> Add a very basic file browser app

- DEVELOPERS.md
Fixes #11 which says it's about docs for functional tests, but there isn't really much to document yet. This just describes the structure of the tests, along the same lines as we did for ehrQL, with the intention that we keep our developer docs update as we add to the tests and test structure.  Airlock's test might not get to be as complex as ehrQL's, but I found an overview of the test structure a useful thing.
> Add some starting docs on test structure to DEVELOPERS.md

- airlock/urls.py
- airlock/views.py
- airlock/workspace_api.py
- tests/integration/test_views.py
- tests/unit/test_workspace_api.py
This way, it can be used for viewing both workspaces and output
requests. A PathItem now takes a reference to container object, which
must have a root path, and a way to generate urls.
Added a top level Workspace object, as the first implementation of such
a Container, will add one for an OutputRequest later.
A workspace is now explict, rather than embedded in that path. As such,
I took the opportunity to explicitly add it as url parameter. The
PathItem.relpath is now always relative to the workspace directory, not
WORKSPACE_DIR.
In anticipation of adding a request file browser view, I renamed the
urls/views to be "workspace".
> Refactor PathItem to have plugable root directory.

- .github/workflows/main.yml
* we didn't spot this in docker-test, as the test passes so we don't use this branch
* job-server currently uses `_`, but uses `docker-compose` instead of `docker compose` so I assume it's related to that
> fix: amend name of containers in failing CI case

- docker/docker-compose.yml
* this compose file is not used for an actual production service, only for testing in the same configuration that we use for prod, so we have no worries about leaking dummy env vars into actual production.
> fix: use .env for "prod" in docker/docker-compose.yml

- airlock/settings.py
- airlock/templates/file_browser/index.html
- airlock/urls.py
- airlock/users.py
- airlock/views.py
- airlock/workspace_api.py
- justfile
- tests/integration/test_views.py
- tests/unit/test_user.py
- tests/unit/test_workspace_api.py
Fixes #21 and #22 
This limits the workspaces shown to only those available to that user, unless the user is an output checker, in which case they can see everything.
The file-browser view currently checks the path it's given, and redirects to the root workspace if the user doesn't have permission for it. All users, including non-logged in users, have access to the root workspace, although it won't show any files to non-logged in users. We probably to redirect non-logged in users to a login view when one is available.
Each child/sibling directory and file checks to ensure user has permission.
Note this makes some assumption about what the user info in the session looks like, so it might need some reworking based on #19.
> Allow users to view and access their own workspaces only

- airlock/middleware.py
- airlock/settings.py
- airlock/templates/base.html
- airlock/urls.py
- airlock/users.py
- airlock/views.py
- tests/integration/test_auth_views.py
- tests/integration/test_views.py
- tests/unit/test_user.py
- tests/unit/test_workspace_api.py
Fixes #20 
- Adds a tiny middleware to add user to the request
- Adds username and is_authenticated to User for use in templates
- A minimal temporary login url/view so that we can login as an output-checker, in absence of actual login flow
- Logout view, with associated template buttons
> Add a logout view

- .gitignore
- .test.env
- docker/Dockerfile
- docker/justfile
- tests/functional/conftest.py
Fixes #40 
I'm not entirely sure I'm happy about installing the chromium dependencies in the image, and at the dev step.  But I don't want to install them in the prod steps, and they need `pip install playwright` to have run first (unless we listed out all the separate dependencies, which is a possibility).
> Run the playwright tests in docker

- airlock/middleware.py
- airlock/settings.py
- airlock/views.py
- tests/integration/test_views.py
Now, all views will redirect if the user is not logged in, except for
login and index (at least for now)
We are not using django auth currently, so this is a DIY version, but
it's pretty simple.
it removes the risk of us forgetting to protect a view.
> Universal login_requires, with exemptions.

- docker/Dockerfile
- docker/docker-compose.yml
* use the jobrunner uid so that our smoke tests can pass
* remove the docker-compose mount that was causing tests to unintentionally pass in CI
> fix: create a workdir in the prod image

- airlock/settings.py
- tests/integration/test_settings.py
This is needed to support a reasonable level of concurrent writes, which isn't an issue now but is best to address before it becomes an issue.
This also gives us a framework for changing other SQLite configuration options like `PRAGMA synchronous = normal` if we choose to do so.
Attaching a signal handler during the settings import is a _bit_ non-standard (normally you'd do it within an app's `ready()` method). But this is a system-wide setting so there's not an obvious app to attach it to and it more naturally belongs with the database config. I can't thing of any specific problems having it here would cause us.
> Configure WAL journal mode for SQLite database

- airlock/templates/file_browser/index.html
- airlock/urls.py
- airlock/views.py
- airlock/workspace_api.py
- tests/integration/test_views.py
- Fix left over use of the term "output_request"
- Explict view urls
This is a url refactor pulled out of WIP change to add submit/reject views.
> url refactor

- tests/factories.py
- tests/functional/test_workspace_pages.py
- tests/integration/test_old_api.py
- tests/integration/test_views.py
- tests/unit/test_workspace_api.py
The initial class based factories were awkward to use. This change refactores them into top level functions.
They now return the core objects directly, rather than an odd Factory object that looked like but wasn't a real object.
Also removed a couple of one line fixtures that didn't add much beyond calling the factory.
This is deliberate move away from a FactoryBoy style factory api to more customisable function based one.
> Refactor the test factories

- airlock/api.py
- airlock/templates/requests.html
- airlock/views.py
- local_db/api.py
- tests/integration/test_views.py
- tests/unit/test_api.py
Previously, the same function retrieved both sets.  Now, there are
separate API functions, and the Eequests page lists them separatedly.
Specifically, as now an author who is also and output checker cannot
review their own request, then those requests are exclude from the "to
review" list.
> Split API for authored requests vs requests to review

- airlock/forms.py
- airlock/templates/file_browser/index.html
- airlock/views.py
- tests/factories.py
- tests/integration/test_views.py
- tests/unit/test_forms.py
Fixes #77 
Adds a modal to the "Add file to request" button, with an option to select a file group, or to add a name to create a new one. 
For now, in the release request view, I've added a button and modal to view the file groups. I expect this will change with the new tree browser UI, so this is intended to be just a temporary (and easily removable) way of seeing which files have been added to which groups.
> Add support for adding a file to a new or existing file group on a request

- airlock/file_browser_api.py
- airlock/settings.py
- airlock/templates/file_browser/index.html
- airlock/templates/file_browser/tree.html
- airlock/views.py
- tests/integration/test_views.py
- tests/unit/test_file_browser_api.py
- minimal functional implementation, not pretty
- uses <details>, so no js needed
- can switch at run time to test, but defaults to new UI
In order for the template to be able to know if the current item in the
tree is, or is a parent of, the currently selected path, I added the
ability to designate a currently selected path to PathItem, as we can't
express that logic cleanly in the DTL.
Note: supporting both UIs behind a feature flag intended to be short
lived, so that code should be deleted soon.
> Add tree base navigation UI

- airlock/api.py
- old_api/__init__.py
- tests/conftest.py
- tests/unit/test_api.py
They didn't really belong in the main API, as they're only used for
talking to job server.
> Move utility functions from api.py to old_api

- airlock/settings.py
- airlock/templates/base.html
We achieve this by converting them into warnings and then relying on our "zero warnings in tests" enforcement to catch them.
This means it's still possible to exploit the default missing variable behaviour when hacking around locally, but it shouldn't be possible to get these into production. And it should be obvious from the console output that there are missing variables.
Closes #84
> Be strict about missing template variables

- airlock/api.py
- local_db/api.py
- tests/unit/test_api.py
Update the two places we mutate state to mutate the object.
Manually made Workspace hashable, for convenience in tests, but also it
is just one bit of immutable data.
> Unfreeze core objects.

- airlock/api.py
- airlock/file_browser_api.py
- airlock/templates/file_browser/index.html
- airlock/templates/requests.html
- airlock/templates/workspaces.html
- airlock/urls.py
- airlock/views.py
- tests/integration/test_views.py
- tests/unit/test_file_browser_api.py
A bevy of pre-factors and cleanups in prepartion for support filegroups in
navigation.
- **Move selected path into container**
- **Add UrlPath type to use for all relative url paths**
- **Make breadcrumbs include root**
- **Refactor url routing**
> container clean ups

- airlock/templates/file_browser/index.html
- airlock/templates/login.html
- airlock/views.py
- pyproject.toml
- requirements.dev.in
- requirements.dev.txt
- tests/factories.py
- tests/integration/test_auth_views.py
- tests/integration/test_views.py
Adds coverage for templates, using the existing django_coverage_plugin, but with a tweak to handle slippers components.
This means we (hopefully temporarily) have our own [fork](https://github.com/opensafely-core/django_coverage_plugin) of the plugin, until [this PR](https://github.com/nedbat/django_coverage_plugin/pull/93) gets in. Without it, any slippers component end tags that are on their own line - which is lots of them - get marked as uncovered.
As a result of writing the tests for the uncovered template lines, I found a breadcrumbs block in the login template that was unused, and noticed that if you go to the login page when you're already logged in, you weren't getting redirect anywhere, you just got the login page again.
> Add coverage for django templates

- DEVELOPERS.md
- airlock/templates/base.html
- airlock/templates/file_browser/index.html
- airlock/templates/requests.html
- airlock/templates/workspaces.html
- assets/templates/_components/button.html
- tests/conftest.py
- tests/functional/test_e2e.py
- tests/integration/test_views.py
Locally these two new e2e tests take 6.5s to run; that will be better when we've settled on a UI, but for now it seems worth running them with the ui_options fixture.
Fixes #79
> End to end tests for creating, releasing and rejecting requests

- airlock/api.py
- airlock/templates/file_browser/index.html
- airlock/views.py
- tests/functional/test_e2e.py
- tests/integration/test_views.py
Adds a button for the current release request, if there is one.
Fixes #106 
Also adding a file to a request now redirect back to the workspace page for that file (which now has the link for the current request) and the "add file to request" button is disabled.
> Add link to current request from workspace view

- airlock/settings.py
- pyproject.toml
Somehow in #80 I managed not to commit the settings and pyproject.toml config that actual made the template coverage plugin run :facepalm:
> Add the settings and config for django-coverage-plugin

- airlock/templates/file_browser/csv.html
- airlock/templates/file_browser/index.html
- **Render csv using plain html templates**
- **Make csv table headers sticky**
Using components, a 3k line csv took ~6s to render. After this change, about 0.25s
> Faster csv rendering

- DEVELOPERS.md
- airlock/settings.py
- airlock/urls.py
- requirements.dev.in
- requirements.dev.txt
But only in dev.
Also, it is not on by default, but setting DJANGO_DEBUG_TOOLBAR env var will do
all the the things needed to enable it.
Also included the template profile extension, as that was my original
motivation.
> Bring back django debug toolbar

- .test.env
- DEVELOPERS.md
- docker/Dockerfile
- docker/justfile
- tests/__init__.py
- tests/functional/conftest.py
tl;dr There were 2 fiddly things involved in this:
1) getting playwright to run with an old browser version
2) getting the old browser version (google don't make old chrome versions easily available)
1) Playwright by default only runs with the latest stable browsers.
An [executable_path](https://playwright.dev/python/docs/api/class-browsertype#browser-type-executable-path) can be specified when launching a playwright browser, however, the pytest-playwright plugin doesn't provide a way to pass this option.
(Note that the PLAYWRIGHT_BROWSERS_PATH env var seemed promising initially, but is a way to install the browser binaries that playwright expects to a custom path, and/or to specify that path. Playwright only runs with the latest stable browsers by default, so we can't just point it at a …
> Run playwright tests with chrome v108

- airlock/api.py
- airlock/file_browser_api.py
- airlock/templates/file_browser/index.html
- airlock/views/helpers.py
- airlock/views/request.py
- tests/functional/test_e2e.py
- tests/integration/views/test_request.py
- tests/unit/test_file_browser_api.py
Uses the existing `contents_url`, and the default for the download filename (i.e. uses the existing filename). I don't think there's a need to include group names or paths in the downloaded filename.
As discussed, only output-checkers can download release request files, and only for requests that they did not author. We don't restrict the types of files that can be downloaded by output-checkers. No workspace files can be downloaded by anyone. 
Fixes #126
> File downloading

- airlock/file_browser_api.py
- tests/unit/test_file_browser_api.py
Previously, we walked the file tree as we recursed down, calling
`iterdir()`, `is_dir()`, and `is_file()` on the way. For large workspace
trees, this was very slow.
Instead, we now get a list of all relative *paths* at the start,
and then walk down the *paths*, just processing them as strings, not
hitting disk.  This is similar to how we built the tree for each
filegroup before, from a flat list of paths in the db. So that method
had been extracted as get_path_tree(), made more general, and is now
used by both get_workspace_files and get_request_files.
As we do not want to call `is_dir()` to detect directories, we instead
use a heurstic based on the path.
- if it has descendant paths, it is a directory
- if it has no descendants and no suffix, it is a directory.
This heuristic is not …
> Optimize workspace tree building

- airlock/business_logic.py
- example-data/dev_users.json
- tests/functional/conftest.py
- tests/functional/test_workspace_pages.py
- tests/unit/test_business_logic.py
As per #146, this change only shows your specific workspaces on the
index page, and in alphabetical order.
> Improve workspace index

- airlock/login_api.py
- tests/functional/test_login.py
- tests/integration/test_auth_views.py
This will keep a TLS connection open and amortize the DNS/TLS/tcp connection
costs.
> Use a session for job-server requests

- local_db/management/commands/backpopulate_file_id.py
- tests/integration/management/commands/test_backpopulate_file_id.py
The previous version (and its test code) was based on an incorrect understanding of where files used to be stored.
> Fix `backpopulate_file_id` command

- airlock/users.py
- tests/factories.py
- tests/functional/conftest.py
- tests/functional/test_e2e.py
- tests/integration/conftest.py
- tests/integration/views/test_request.py
- tests/integration/views/test_workspace.py
- tests/unit/test_business_logic.py
- tests/unit/test_user.py
In preparation for pushing more user validation checks down into the BLL, this change refactors test user creation to be easier and more consistant, now that User.workspaces must be a dict.
> Refactor how we create and use test users

- airlock/business_logic.py
- airlock/file_browser_api.py
- tests/integration/views/test_workspace.py
- tests/unit/test_business_logic.py
- **Refactor Filegroup.files into a dict**
- **Add get_request_file method**
> lookup request file

- .github/dependabot.yml
> Make dependabot ignore pydantic major version updates

- services/tracing.py
- tests/test_tracing.py
Workaround a bug in docker-compose
> Strip quotes from OTEL_EXPORTER_OTLP_HEADERS values

- DEVELOPERS.md
- airlock/business_logic.py
- airlock/file_browser_api.py
- airlock/views/request.py
- airlock/views/workspace.py
- services/tracing.py
- tests/integration/views/test_request.py
- tests/integration/views/test_workspace.py
- tests/test_tracing.py
- tests/unit/test_file_browser_api.py
Adds an `@instrument` function decorator, following [this post](https://betterprogramming.pub/using-decorators-to-instrument-python-code-with-opentelemetry-traces-d7f1c7d6f632), plus some extra options to retrieve arg/kwarg values from the function signature, so we can add in the workspace name / request id.
Adds tracing for all request views, workspace views, `get_workspace_tree` and `get_request_tree`. Leaving the rendering for another PR.
> Custom otel traces

- airlock/file_browser_api.py
- airlock/views/request.py
- airlock/views/workspace.py
- services/tracing.py
- tests/test_tracing.py
By using the inspect module to identify the bound arguments passed to the function, we don't need to separate arg and kwarg attributes, and we can handle cases different types of function call, where keywords aren't enforced. We can also now handle keywords captured in a **kwargs parameter.
> Refactor the instrument decorator to use inspect to find arguments

- dotenv-sample
- gunicorn.conf.py
- justfile
- services/tracing.py
- tests/test_tracing.py
The value of PYTHONPATH made no sense. And its only required to be present in the env, it can be set to nothing.  So I incorporated that in the code
Likewise, set a default DJANGO_SETTINGS_MODULE in the right place.
Also flipped OTEL_EXPORTER_CONSOLE to off by default, as its very
verbose.
> Clean up the otel config

- airlock/file_browser_api.py
- airlock/settings.py
- airlock/templates/file_browser/contents.html
- airlock/views/request.py
- airlock/views/workspace.py
This makes two changes:
- only set X-Frame-Options: SameOrigin for the two views that need it
rather than globally
- disable everything in frames, including js, with an exception for csv
files, which a) we control the rendering of and b) uses some small
amount of js, and likely will use more in the future.
The motivation as blocking js in html from executing.
> Tighten up iframe security

- airlock/business_logic.py
- airlock/templates/file_browser/contents.html
- airlock/urls.py
- airlock/views/__init__.py
- airlock/views/request.py
- tests/functional/test_e2e.py
- tests/integration/views/test_request.py
- tests/unit/test_business_logic.py
* I think this fixes https://github.com/opensafely-core/airlock/issues/137
> create file approve & reject urls

- airlock/templates/file_browser/contents.html
Importantly, this allowed it to share the brower cache with the host
page. Without, nothing was ever cached!
> Add allow-same-origin to the iframe sandboxing

- airlock/templates/file_browser/csv.html
Fixes #216 
The template, and uses the upstream `_datatables.js` from job-server to handle the sorting/filtering/search/pagination and styling of the table.  That script adds the simple-datatables table, and replaces any server-side pagination buttons from django with new elements. All the pagination is actually done client-side. We could pass a paginator from the renderer, but the only possible benefit that I could see would be to show the correct "Page 1 of N" text instead of "Page # of #" before the js has time to replace that content.
I couldn't get the csv.html template to recognise the slippers components as valid block tags, so it does the icons and buttons longhand.
> Use simple-datatables for rendering CSV files

- docker/Dockerfile
ppa domains changed in 2022; although the old ones were supposed to remain indefinitely, they're currently inaccessible; but we should update to the new one anyway
https://blog.launchpad.net/ppa/new-domain-names-for-ppas
> Update ppa domain name

- airlock/settings.py
- django_sqlite3_backport/base.py
- justfile
- tests/integration/test_settings.py
This involves backporting some SQLite improvements from unreleased Django 5.1 and then using them to configure SQLite more gooder.
Closes #248
> Improve SQLite configuration

- airlock/business_logic.py
- old_api/__init__.py
- tests/unit/test_business_logic.py
This allows jobserver to use the airlock request ID when it creates a release.
Related job-server PR: https://github.com/opensafely-core/job-server/pull/4295
> Send airlock request id to jobserver when releasing files

- airlock/file_browser_api.py
- tests/unit/test_file_browser_api.py
This occured when a) the target was an empty dir and b) you were are
using HTMX and thus selected_only=True.
Fixes #260, and adds test.
> Fixes empty directory exception

- airlock/templates/file_browser/csv.html
As per the docs[1] this is converted to an integer if numeric. Seems to
work.
Fixes #251
[1] https://fiduswriter.github.io/simple-datatables/documentation/Getting-Started#initial-data
> Fix csv column sorting by adding a data-order attribute

- airlock/business_logic.py
- airlock/file_browser_api.py
- airlock/lib/git.py
- airlock/renderers.py
- airlock/settings.py
- airlock/templates/file_browser/index.html
- airlock/urls.py
- airlock/views/code.py
- pyproject.toml
- tests/conftest.py
- tests/factories.py
- tests/integration/views/test_code.py
- tests/unit/test_business_logic.py
- tests/unit/test_file_browser_api.py
- tests/unit/test_renderers.py
This is a preview/spike of the code browser.
We need https://github.com/opensafely-core/job-runner/issues/701 to be done before we can get the commit we need to link to the right code browser.
So there are no links that that will take you to the code browser.  To test it, you will need to:
- add a metadata/manifest.json file to the workspace directory with the contents: `"repo": "https://github.com/opensafely/$REPO"`
- manually navigate to `/code/view/$WORKSPACE/$COMMIT/`
It rather large as we import some code from job-runner, and add a bunch of new views and logic.
> Code Browser first pass

- .github/workflows/pages-deployment.yml
This skips the pages-deployment workflow if there have been no changes to any files in the docs/ folder or to mkdocs.yml. It also skips running this workflow on the main branch, since the docs are availabe in a deployed airlock anyway and can be checked on the test backend or in the main docs.
Previous test runs with a [mkdocs.yml change](https://github.com/opensafely-core/airlock/actions/runs/8802425009) and a[ docs dir change](https://github.com/opensafely-core/airlock/actions/runs/8802451161) ran the pages deployment as expected. This branch (with no docs-related changes) [did not](https://github.com/opensafely-core/airlock/actions/runs/8802482871).
> Only run pages-deployment if docs have changed

- airlock/templates/file_browser/contents.html
* this means that if a user clicks between a file & a directory, the display will not jump around confusingly
* needs to be full screen size rather than filling the available screen, as we need this element on its own to be able to fill the screen for this to work as expected.
> Set the min-height of a subdirectory to fill the screen

- airlock/file_browser_api.py
- tests/functional/test_e2e.py
- tests/unit/test_file_browser_api.py
We rarely expect >20 files here. Expanding all by default saves the user
clicks, and gives them  a) full view of the status of every file and b)
one click navigation to every file.
They can always collapse if they need to.
> Expand all files in the request tree by default.

- airlock/business_logic.py
- airlock/notifications.py
- airlock/settings.py
- local_db/data_access.py
- tests/conftest.py
- tests/unit/test_business_logic.py
- tests/unit/test_notifications.py
Fixes #256 
Sends notifications  on:
- set status (on moving to any status except pending)
- edit group (editing context/controls)
- add file
- withdraw file
- add comment
For updates (i.e. the last 4 above), notifications are only sent for requests in non-pending state.
Currently update events are not batched, with the exception of context and controls editing (because those are part of the same form). The DAL now returns a list of NotificationUpdateTypes on group_edit to indicate which fields have changed and need to be notified.
> Notifications

- airlock/templates/login.html
Fixes #269 
The form previously asked for "GitHub username or email address". GitHub email address is not always the email address that will work for login. Logging in to job-server with GitHub will populate the user's job-server account with their primary GitHub email. However, they can then change it, and if they do, the new email address will be valid for login, not the primary GitHub one.
We don't want to restrict users to ONLY logging in with GitHub username, as some users may not be very familiar with GitHub and may not know their GitHub username.
> Update login form label

- airlock/file_browser_api.py
- justfile
- scripts/manifests.py
- tests/factories.py
- tests/unit/test_business_logic.py
- tests/unit/test_file_browser_api.py
This is used by default in test factories, but also is exposes as `just
manifests` as a dev tool to create manifests for your local test
workspaces.
> Add support for generating test manifests.

- tests/functional/conftest.py
The default is 5s, but we seem to [occasionally hit that,](https://github.com/opensafely-core/airlock/actions/runs/9003575497/job/24734509934#step:6:3596) so increase it to 10s for individual asserts.
Have verified that if the timeout is set to something unreasonably small (like 1s), it gets the same error as the occasionally failing CI tests
> Increase the global timeout for e2e expect assertions

- airlock/settings.py
- airlock/templates/file_browser/group.html
- airlock/views/request.py
- docs/creating-a-release-request.md
- docs/requesting-a-review.md
- docs/reviewing.md
- tests/functional/test_request_pages.py
Fixes #324 
Hides the form fields for context, comments and controls based on a new SHOW_C3 env variable and setting.
Also updates docs to be consistent with the (temporary) new process. The [minimally-adapted Word doc form](https://docs.google.com/document/d/1uWRiFps6tDA2SpxSxf0C2G9mOVWMQ6TQ/edit?usp=drive_link&ouid=114747311902500453985&rtpof=true&sd=true) should also be reviewed before this is merged.
> Temporarily remove c3 form fields

- airlock/business_logic.py
- airlock/views/code.py
- airlock/views/workspace.py
- local_db/management/commands/backpopulate_file_manifest_data.py
- tests/conftest.py
- tests/factories.py
- tests/integration/management/commands/test_backpopulate_file_manifest_data.py
- tests/unit/test_business_logic.py
This adds a manifest and current_request property, and a from_directory
contructor, which loads the manifest and any current request, and
creates the Workspace object.
This means any Workspace when created will always have a manifest, as
that is required now. This is more consistent, and uncovered a number of
issues.
It will also have any current_request for the user. This is going to be
very useful in template rendering in a coming PR
The idea is that once a workspace is instantiated, it is complete and
has everything available that it might need to then reference.
> Refactor Workspace construction

- airlock/business_logic.py
- airlock/file_browser_api.py
- airlock/templates/file_browser/directory.html
- tests/factories.py
- tests/functional/test_e2e.py
- tests/unit/test_business_logic.py
This uses a datatable to list the contents in a directory. It was spun
out of the multiselect work.
This means we can sort and order on columns, and so I also add size and
modified times for this too, to provide a use case.
There will be other columns coming soon, one for current file state
(unreleased/in-request/released for workspace files,
approved/rejected/withdrawn for request files), as well as a checkbox
column for the multiselect.
> Rework directory view to use datatable

- airlock/business_logic.py
- airlock/file_browser_api.py
- airlock/templates/file_browser/directory.html
- airlock/templates/file_browser/file.html
- airlock/types.py
- airlock/views/request.py
- airlock/views/workspace.py
- tests/factories.py
- tests/integration/views/test_request.py
- tests/unit/test_business_logic.py
- tests/unit/test_file_browser_api.py
- tests/unit/test_renderers.py
This adds a core capability - knowing whether a file is part of the current reqeust and if it has been updated since added.
It uses this new capability to a) decorate the tree with classes for later styling and b) decide if a file can be added to a request or not.
fixes #343
> Add workspace file state detection

- airlock/file_browser_api.py
- airlock/templates/_components/header.html
- airlock/templates/file_browser/file.html
- airlock/templates/file_browser/index.html
- airlock/views/code.py
- airlock/views/request.py
- airlock/views/workspace.py
- justfile
- scripts/manifests.py
- tests/factories.py
- tests/functional/test_code_pages.py
- tests/integration/views/test_code.py
- tests/unit/test_file_browser_api.py
Adds a link to view code from workspace or request files.
Uses a return_url query param so user can go back to whichever file they came from.
I've also updated `just manifests` to create a local git repo for test workspaces as well as the manifest.json, which mean that code links from workspaces will work. 
However, any existing test request files will have been created with old dummy commits from the manifest.json, so you also need to run `just manage backpopulate_file_manifest_data` to fix them. (If you see "Could not update manifest.json data..." messages, it's probably because you have requests with files that no longer exist in the workspace folder)
> Add code browser links

- justfile
I should have done this as part of 303b68c6 but I missed it.
> Fix Ruff deprecation warning in `just fix`

- airlock/business_logic.py
- airlock/settings.py
- tests/unit/test_business_logic.py
Fixes #342
Previously we had a default org/repo that was sent to job-server; now we only send these values if they're explicitly set as env variables, and we let job-server deal with any others. This means that the test backend can set the org/repo that should be used for creating issues (i.e. not a real output-checking repo), and job-server can decide which repo to use based on the organisation that the workspace belongs to (which airlock doesn't have knowledge of).
Depends on job-server PR https://github.com/opensafely-core/job-server/pull/4372
> Support managing GitHub issues in different repos per organisation

- airlock/business_logic.py
- airlock/file_browser_api.py
- airlock/templates/file_browser/file.html
- airlock/templates/file_browser/request.html
- airlock/types.py
- airlock/views/request.py
- airlock/views/workspace.py
- local_db/data_access.py
- local_db/migrations/0006_filereview.py
- local_db/migrations/0009_alter_auditlog_type_alter_filereview_status_and_more.py
- local_db/models.py
- tests/integration/views/test_request.py
- tests/unit/test_business_logic.py
- tests/unit/test_file_browser_api.py
- **Rename FileReviewStatus to UserFileReviewStatus**
- **Refactor FileReview.reviews to be a dict with username key**
- **Make request.output_files_set a dictionary**
- **Add RequestFileReviewStatus to capture the full state**
- **Clean up old code still using container.request_filetype**
- **Expose request states in request tree.**
> Track and expose request file state in tree

- airlock/business_logic.py
- tests/factories.py
- tests/functional/test_e2e.py
- tests/functional/test_request_pages.py
- tests/unit/test_business_logic.py
For older manifests, the top level repo may be None, but it can be retrieved from the output file data.
> Fallback to fetching repo from first manifest output

- airlock/static/assets/file_browser/csv.js
- airlock/templates/file_browser/csv.html
Remove pagination, which doesn't affect load times since it was all being done on the frontend in datatables anyway.
JS updated to wait until an element of the loaded datatable is present before hiding the loading spinner (avoids displaying the unformatted table before the datatable has loaded).
> Disable CSV pagination

- airlock/business_logic.py
- airlock/file_browser_api.py
- airlock/renderers.py
- airlock/templates/file_browser/file.html
- airlock/templates/file_browser/plaintext.html
- airlock/views/code.py
- airlock/views/request.py
- airlock/views/workspace.py
- tests/unit/test_business_logic.py
- tests/unit/test_renderers.py
Fixes #408, which wasn't really a problem with CSV rendering, but a problem with the file that had been labelled as CSV. This will give users the option to view files in plain text, which should make badly formatted CSVs more readable without downloading.
> Option to view any allowed file as plain text

- airlock/business_logic.py
- tests/unit/test_business_logic.py
- tests/unit/test_notifications.py
When a request is re-submitted, it's useful to send that to job-server so it can differentiate between and inital submission (which creates and issue) and a re-submission (which updates an issue).
> Add a resubmitted notification type

- airlock/renderers.py
- airlock/static/assets/file_browser/csv.js
- airlock/templates/file_browser/csv.html
- airlock/templates/file_browser/plaintext.html
- tests/unit/test_renderers.py
Fixes #416
simple-datatables can only render tables with equal numbers of columns in each row. If a CSV output file has different columns per row (usually because it's not proper tabulated data), the datatable will fail to initialised. This was resulting in the page appearing to hang on the "loading ..." message.
This is addressed in a couple of ways:
1) Adds a `setTimeout` in the JS which waits for 5 seconds, and if the datatable element hasn't been found by then, it just unhides the table element anyway (which will show the plain html table if datatables failed to load).
2) Checks the column counts per row in the CSV renderer, and stops datatables being used at all if the counts aren't the same (which avoids having to wait 5 seconds when we know there's going to be a problem).
This does …
> Handle bad csvs

- airlock/views/request.py
Missing `request.user` meant that the `user_approved` class was not being added to approved files in the tree.
This is blocking me from adding icons to show the correct state for a file in the tree.
> Fix missing request.user information

- airlock/templates/file_browser/index.html
The method was removed here:
https://github.com/opensafely-core/airlock/commit/8be977883a16afd8
But the template code which used it was added in a separate PR here:
https://github.com/opensafely-core/airlock/commit/88eb7d5537a4b49d
So while each PR's tests passed, their merge didn't.
> Use context var rather than removed method

- airlock/templates/file_browser/index.html
- tests/functional/test_request_pages.py
The return request isn't an htmx one, so these attributes - probably a copy/paste error - were causing it to load the response into the button element.
> Remove hx attributes from return button

- airlock/business_logic.py
- old_api/__init__.py
- tests/integration/test_old_api.py
- tests/unit/test_business_logic.py
Pass the request id to `old_api.create_release` so that we can log it. Avoids having to retrieve the request id from the `release_json`, which could be incorrect.
fixes #426
> Fix bug logging job-server errors

- airlock/templates/file_browser/index.html
- tests/functional/test_e2e.py
Adds a modal before a request is first submitted (but not when it is resubmitted) which asks the user to confirm that they have read the documentation and will abide by the relevant principles.
Subsequent PRs will add a form to capture more information at this step.
Relates to #403
> Add confirmation modal before first submission

- airlock/views/request.py
- tests/integration/views/test_request.py
If there are no output files on a request, there's nothing to be reviewed. The method for all_files_reviewed_for_user returns True, but we don't want to remind users to complete their review when there was nothing to review.
We also don't want to show this to authors at all.
> Only show the complete-review reminder where there are files to review

- airlock/business_logic.py
- airlock/views/request.py
- docs/request-states.md
- local_db/data_access.py
- tests/functional/conftest.py
- tests/functional/test_code_pages.py
- tests/functional/test_request_pages.py
- tests/integration/views/test_request.py
- tests/unit/test_business_logic.py
Fixes #424 
- Update the definition of active request to include all author and reviewer owned statuses
- Hide withdraw file button if request is not author-editable
- Update BLL and DAL so that adding and withdrawing files are only allowed in author-owned statuses
- Remove state transition from REJECTED to APPROVED
> Update definition of active requests and prevent adding/withdrawing in submitted status

- airlock/templates/file_browser/directory.html
- airlock/templates/file_browser/file.html
- airlock/views/workspace.py
- tests/functional/test_e2e.py
- tests/integration/views/test_workspace.py
Fixes #438 
A file can only be added from a workspace with a current request if that request is in pending or returned status (i.e. author-editable ones). We already have appropriate checks and error messages if a file can't be added due to request status, but this disables the button.
Also adds similar checks for the "add files" multiselect and disables it if there is an active request in non-editable status. It doesn't check there are add-able files, since the modal already shows the file state for each selected file.
> Only show "add file(s)" buttons when a request is in pending or returned statuses

- airlock/static/assets/file_browser/index.css
- airlock/templates/file_browser/file.html
- Show the status icon next to the status name in the file browser
- Simplify the status for supporting and withdrawn files
> Show status icons in file browser

- tests/factories.py
If you call `create_request_at_status` with status `WITHDRAWN` and `withdrawn_after` as an invalid value (in my case `SUBMITTED`), you currently don't get an error, you get a valid request in the withdrawn_after status (i.e. `SUBMITTED`), which can lead to misleading failures in the tests you're working on. 
We could also put a bunch of `bll.set_status()` calls in the relevant places to trigger the actual Exceptions for this stuff, but this is shorter (& I think it only applies to WITHDRAWN).
> Add a small guard rail

- airlock/templates/file_browser/directory.html
> Hide multiselect checkbox for directories

- justfile
- scripts/manifests.py
- tests/factories.py
Avoid re-creating dummy github repos and commits for workspaces with real github repo urls in their manifest.json. This means we can mimic a real github repo locally and update manifests when we edit local files without borking the valid repo/commit info.
> Update the manifests.py script for real repos

- airlock/business_logic.py
- airlock/settings.py
- airlock/templates/file_browser/directory.html
- airlock/templates/file_browser/file.html
- airlock/templates/file_browser/index.html
- airlock/templates/file_browser/workspace.html
- airlock/templates/workspaces.html
- airlock/users.py
- airlock/views/workspace.py
- example-data/dev_users.json
- tests/factories.py
- tests/functional/conftest.py
- tests/functional/test_code_pages.py
- tests/functional/test_e2e.py
- tests/functional/test_request_pages.py
- tests/integration/test_auth_views.py
- tests/integration/test_middleware.py
- tests/integration/views/test_workspace.py
- tests/unit/test_business_logic.py
- tests/unit/test_login_api.py
- tests/unit/test_user.py
Fixes #437 
Prevent requests being created/edited (by authors) for archived workspaces and workspaces for projects.
For now, output-checkers can continue to action requests for archived/inactive workspaces. Currently workspace info is only retrieved for the user's workspaces, so if we wanted to prevent this, we'd need to call a new job-server endpoint to get workspace info. We may well want to do that later, but for now I've limited this PR to the info we have available for a user.
Workspace/project status is shown on the workspace list (with inactive projects last, and archived workspaces last within a project):
In the workspace, project/workspace status is also displayed:
> Restrict actions on archived workspaces and inactive projects

- airlock/templates/file_browser/index.html
> Reorder buttons

- airlock/templates/file_browser/index.html
- example-data/dev_users.json
- tests/functional/test_e2e.py
- tests/functional/test_request_pages.py
I've adapted the wording from the warning we give when withdrawing a request. Possibly we want to say something different though?
This suffers from the modal button sizing issue which we already know about and presumably will fix at some point:
Closes #463
> Add confirmation before rejecting request

- airlock/business_logic.py
- local_db/data_access.py
- tests/unit/test_business_logic.py
fixes #461 
Remove notifications for updates. We now only send notification for status changes. I've kept the option to send updates with a notification but reworked it a little, so in future we can send additional update messages along with a status change notification. Job-server handles these in [this PR](https://github.com/opensafely-core/job-server/pull/4443).
> Send notifications for status changes only

- airlock/templates/add_files.html
This happened in the presence of long filenames and looked silly.
Before:
After:
Closes #465
> Prevent form labels wrapping

- airlock/templates/requests.html
* this is only for a slightly unusual error state, in which the release process has failed (during the interaction with job server)
* most of the time, most output checkers should not need to worry about this, so hide it from the default view
* fixes #477
> Hide "Approved Requests" card if no requests

- airlock/views/request.py
* fixes https://github.com/opensafely-core/airlock/issues/496
> Successfully returning a request is a success, not an error

- airlock/nav.py
- airlock/settings.py
- airlock/templates/_includes/header.html
- airlock/views/auth.py
- tests/functional/conftest.py
- tests/functional/test_e2e.py
- tests/functional/test_login.py
Gives us a menu option to switch between any of the available users in a `dev_users.json` file.
If `AIRLOCK_API_TOKEN` is set (i.e. in prod or prod-like envs - anything with a connected job-server), `AIRLOCK_DEV_USERS_FILE` is always None, there will be no DEV_USERS, and the menu item won't be visible.
No AIRLOCK_API_TOKEN in .env:
With AIRLOCK_API_TOKEN in .env:
> Allow easy switching between users in local dev environments

- airlock/templates/file_browser/file.html
- tests/functional/test_e2e.py
This makes it more obvious how to reset a file's review status to "Undecided".
Closes #466
> Use three-way pill for file status

- airlock/templates/file_browser/group.html
This removes the client side validation and means that if you click the comment button without entering any text, it'll hit the form validation. I think this is OK, since it shouldb't be that common to try to add comments without putting something in the box first.
> Hide required asterisk for comment field

- airlock/views/request.py
To reproduce the original issue:
* As an output checker, approve/reject all files in a release request so that the confirmation message "All files reviewed. Your review can now be completed." is displayed.
* In the left-hand tree view, click back and forward between two files which updates the page contents without reloading the page.
* Do something to reload the page (pressing F5 will do).
* Note the stack of confirmation messages, whose count corresponds to the number of times you clicked in the left-hand tree view.
To my mind it's a slightly unusual use of the messages framework to set messages repeatedly on GET, based on the current state of the system. Normally, messages are set in response the changes of state, usually via a POST. But in any case, preventing this messages being set …
> Prevent extraneous alerts stacking up

- airlock/business_logic.py
- airlock/templates/file_browser/group.html
- airlock/users.py
- airlock/views/request.py
- airlock/views/workspace.py
- tests/functional/test_request_pages.py
Disable editing of context/controls for author when the request is under review
Fixes #537
Hide comments unless allowed to comment
Fixes #539 
Commenting is only allowed if a request is
- not final
- is under review, and the user is an output-checker
- is in draft, and the user has permission to accesss the workspace
> Disable editing of context and controls for author when the request is under review

- airlock/views/request.py
- tests/functional/test_request_pages.py
Fixes #497 
Plus a drive-by fix for the complete-review reminder message if the request isn't currently in an under review message.
> Hide file review buttons when request is not under review

- airlock/templates/_components/header.html
Fixes #436 
Request status now shown in a pill in the header
> Show request status in request header

- airlock/static/assets/file_browser/tree.css
Align file icons with folder icons at the same level
Before:
After:
> Fix indentation of files in tree view

- airlock/renderers.py
- tests/unit/test_renderers.py
This involves a bit of refactoring as there is now more than one argument to `open()` which we need to modify depending on whether we're in text or binary mode.
Closes #473
> Handle invalid UTF-8 in plain text view

- airlock/static/assets/datatable-loader.js
- airlock/templates/activity.html
- airlock/templates/file_browser/csv.html
Makes the datatable loading script for hiding the raw table before a datatable loads more generic, and reuse it for the activity log datatable.
Fixes #478
> Reuse CSV datatable delayed loading for activity log

- airlock/templates/file_browser/index.html
- airlock/views/request.py
- tests/integration/views/test_request.py
Adds a new component for showing an alert message when an action is required on a request.
Currently these are:
1) Output checker has reviewed all files and needs to complete their review
2) Output checker completes the second review for a request and the request now needs to be progressed by returning, rejecting or releasing.
Releasing is available (all files approved twice):
Releasing not available (some files rejected by at one or both reviewers):
Fixes #503
> Alerts on the request pages when something needs to be actioned

- airlock/business_logic.py
- tests/factories.py
- tests/integration/management/commands/test_backpopulate_file_manifest_data.py
- tests/integration/test_old_api.py
- tests/integration/views/test_request.py
- tests/integration/views/test_workspace.py
- tests/unit/test_business_logic.py
- tests/unit/test_file_browser_api.py
- tests/unit/test_renderers.py
In a few places, we use the DAL directly from the test factories to manipulate state. This is convenient, but has two drawbacks:
1) It potentially allows invalid states to be created
2) It requires duplicating some logic, particularly the creation of event logs.
This change moves to using only BLL methods to manipulate state. This requires us to respect some limitations that previously we had ignored. Most of that is handled in the test factories, but in one case a test needed a fair bit more setup to get into the right state.
Note that we still use the dal in a couple of places in the test factories, for creating filegroups and audit events directly. However, the former is very simple, and the latter has no BLL equivalent.
> Refactor factories to use BLL for all state manipulation, rather than the DAL.

- DEVELOPERS.md
- airlock/static/assets/activity.js
- airlock/static/assets/datatable-loader.js
- airlock/templates/activity.html
- airlock/views/request.py
- assets/justfile
Fixes #499 
Add pagination to the activity log and limit the number shown per page to 10 (this required a small change to upstream job-server assets).
I've reused the pagination code we used to have for CSV datatables.
Also QoL change to the assets justfile to make testing upstream asset changes easier.
> Paginate the activity log

- airlock/business_logic.py
- airlock/templates/_components/header.html
- airlock/templates/requests.html
- airlock/views/request.py
- tests/functional/test_e2e.py
- tests/integration/views/test_request.py
Fixes #253 
Show the request status and the current reviewer's progress on the request list page for each outstanding request. If their review isn't complete it says so (including if they have reviewed all files but not pressed the "Complete review" button). If their review is complete, I've assumed it's obvious from the request status and we don't need to say so.
Also made the user requests, returned and approved ones show the status in the same format as the outstanding ones.
> Show request review progress on requests list page

- tests/functional/test_e2e.py
The problem was interacting with fields in the table before the DataTables plugin had finished rendering. This would sometimes cause the wrong checkbox to be selected which lead to very confusing errors.
> Fix flaky test

- airlock/templates/file_browser/_includes/directory_table/repo.html
- airlock/templates/file_browser/_includes/directory_table/request.html
- airlock/templates/file_browser/_includes/directory_table/workspace.html
- airlock/templates/file_browser/directory.html
Adds the file type to the request directory table - fixes #479 
Remove metadata columns from the repo directory table - fixes #551 
Plus some refactoring of the table into individual workspace/request/repo files. This means a bit of repetition, but makes the individual templates cleaner.
> Directory table columns for request/repos

- airlock/views/request.py
- airlock/views/workspace.py
The root of a code repo doesn't contain any displayable information,
so it was showing a blank page, which was somewhat confusing to land
on from the source code link in a workspace/request file.
As every linked coderepo should have a project.yaml, and that's the
most likely place a user is going to want to start from when
browsing the source code, we link directly to the project.yaml from
the workspace/request files, instead of to the root.
> Change source code links to go directly to project.yaml

- airlock/business_logic.py
- airlock/forms.py
- airlock/management/commands/audit.py
- airlock/templates/file_browser/group.html
- airlock/templates/file_browser/workspace.html
- airlock/views/request.py
- airlock/views/workspace.py
- local_db/data_access.py
- local_db/migrations/0018_filegroupcomment_visibility.py
- local_db/models.py
- tests/integration/views/test_request.py
- tests/integration/views/test_workspace.py
- tests/local_db/test_data_access.py
- tests/unit/test_business_logic.py
This change ensures that users don't see audit messages that they shouldn't see.
It uses exactly same logic as previous work hiding comments/votes from users. So, this means
- Request author and other non-output-checkers cannot see private comment audit logs from any turn
- When in INDEPENDENT phase, output-checkers cannot see each others audit logs for votes/comments from the current turn
- When in CONSOLIDATING phase, output-checkers can see each others audit logs for votes/comments from the current turn, but the author cannot
- When in AUTHOR phase, authors can now see the audit logs votes and *public* comment from the previous turn.
- When in COMPLETE phase, all items from all turns are visible, subject to private/public rules
Fixes #534
> Filter out audit logs that a user cannot see

- airlock/business_logic.py
- airlock/forms.py
- airlock/management/commands/audit.py
- airlock/templates/file_browser/group.html
- airlock/templates/file_browser/workspace.html
- airlock/views/request.py
- airlock/views/workspace.py
- local_db/data_access.py
- local_db/migrations/0018_filegroupcomment_visibility.py
- local_db/models.py
- tests/integration/views/test_request.py
- tests/integration/views/test_workspace.py
- tests/local_db/test_data_access.py
- tests/unit/test_business_logic.py
This is an identical resubmission of https://github.com/opensafely-core/airlock/pull/570
I accidentally merged that then reverted. This is that with clean history, and rebased on all the main change since then.
- **Factor out the core visibility logic to be reusable**
- **Remove activity log from workspace.**
- **Switch tests that assert against audit logs to use the DAL**
- **Rename get_audit_log to get_request_audit_log**
- **Filter audit logs by visibility**
- **Cover the new filtered audit logs in tests**
- **Clarify filter_visible_items logic**
- **Rename CommentVisibility to Visibility**
- **Fix visible logic when phase is COMPLETE**
- **Fix bug in comment descriptions and class**
- **Refactor the comment visiblity pills**
- **Fix comment typos**
> Filter audit logs for visibility

- airlock/business_logic.py
- airlock/templates/file_browser/file.html
- airlock/views/request.py
- tests/functional/test_e2e.py
- tests/unit/test_business_logic.py
After a user submits a review, the request changes status (to PARTIALLY_REVIEWED or REVIEWED). In these statuses, users can still change their votes. However, we want to prevent them from re-setting votes to undecided, to avoid the possibility of returning a request with incomplete file reviews.
Also includes some refactoring of the voting button logic in the view to make the template logic simpler.
> Prevent resetting of file votes after a review has been submitted

- airlock/file_browser_api.py
- airlock/templates/file_browser/_includes/directory_table/workspace.html
- tests/functional/test_e2e.py
* updating files introduces significant complications into the multiselect, let's disable it for now & create a ticket to implement that later
* researchers can update files individually from the file view
> Hide multiselect for updated files

- airlock/permissions.py
- airlock/policies.py
We want to extract to a common location all of our checks on whether a user can do a thing. Some of these checks are permissions (e.g. a user never has permission to review a request if they are not an output checker). However, some are dependent on the state of the request or file that the user is trying to act on. These change, and so aren't solely user- dependent permissions. E.g. a user may have permission to review a request, but can't actually review at this stage because the request is in RETURNED status, and can only be worked on by the author.
This splits permissions and policies, where policies are checks on whether a permitted user can peform an action on a request/file at this particular time/status.
> Refactor permissions.py into policies and permissions

- airlock/business_logic.py
- airlock/enums.py
- airlock/file_browser_api.py
- airlock/forms.py
- airlock/types.py
- airlock/views/request.py
- airlock/views/workspace.py
- local_db/data_access.py
- local_db/migrations/0002_requestmetadata_status.py
- local_db/migrations/0005_requestfilemetadata_filetype.py
- local_db/migrations/0006_filereview.py
- local_db/migrations/0009_alter_auditlog_type_alter_filereview_status_and_more.py
- local_db/migrations/0018_filegroupcomment_visibility.py
- local_db/models.py
- tests/factories.py
- tests/functional/test_code_pages.py
- tests/functional/test_e2e.py
- tests/functional/test_request_pages.py
- tests/integration/views/test_request.py
- tests/integration/views/test_workspace.py
- tests/local_db/test_data_access.py
- tests/unit/test_business_logic.py
- tests/unit/test_file_browser_api.py
- tests/unit/test_notifications.py
- tests/unit/test_permissions.py
We have a lot of enums in Airlock. In addition to reducing the size of business_logic_layer.py, moving them to their own modules avoids circular imports when various different modules need to use them.
Note: the one enum in old_api/schema.py is left where it is, as we expect to replace old_api at some point in the (nearish?) future.
> Move all the enums to their own module

- airlock/business_logic.py
- airlock/policies.py
- airlock/views/workspace.py
- local_db/data_access.py
- tests/local_db/test_data_access.py
* the UI would not present the option to add a file in the state UNDER_REVIEW. Although the BLL function would accept a file in that state, the BLL's call to the DAL would then correctly reject it
* I believe the existing function in policies.py was derived from the BLL function
> Small add file permission refactor

- airlock/business_logic.py
- airlock/permissions.py
- airlock/policies.py
- airlock/views/request.py
- tests/integration/views/test_request.py
- tests/unit/test_business_logic.py
- tests/unit/test_file_browser_api.py
Refactors permissions and policies for:
- marking a file as undecided (this is a policy only as it's done by the system when a request is returned)
- editing group (adding context/controls)
- creating comments
- deleting comments
Some of the permissions were previously implemented in view/template logic only, especially around comments. This moves them into the BLL, so a bunch of tests also needed updating.
Permissions for deleting comments is also updated, so users can now only delete comments when it their turn (same as for creating comments). This means that comments e.g. can't disappear during a review, or be removed after a request is in a final status.
> Refactor mark undecided, group edit and commenting permissions

- airlock/business_logic.py
- airlock/forms.py
- airlock/permissions.py
- airlock/policies.py
- airlock/templates/file_browser/file.html
- airlock/templates/update_files.html
- airlock/urls.py
- airlock/views/__init__.py
- airlock/views/workspace.py
- tests/functional/test_e2e.py
- tests/integration/views/test_workspace.py
* before this PR, when updating a file we were showing the add file dialogue
* this included filetype & group selectors which were being ignored 
* create (& use) a new multiselect view & form to use for updating files
* refactor the code for re-adding a withdrawn file & updating a file using the new policies/permissions files
* at the moment updating a file is limited to one file, but this lays a lot of the groundwork to implement a multiselect update files button on the workspace view
> Show a sensible dialogue when updating a file

- airlock/business_logic.py
- local_db/data_access.py
- tests/conftest.py
- tests/factories.py
- tests/integration/test_old_api.py
- tests/integration/views/test_request.py
- tests/integration/views/test_workspace.py
- tests/unit/test_business_logic.py
- tests/unit/test_permissions.py
- **Remove ability to customise the id of a request**
- **Remove bll._create_release_request**
- **Separate factories.create_user use cases**
> Remove factories request creation workaround

- justfile
This follows on from #617 by adding a single `just` command which does the right thing with respect to compiling requirements files.
There's now no need for a separate `pip-compile` command: it's easy enough to run specific `pip-compile` commands by hand if you really need to, and the new command echos what it's doing for transparency.
The command name itself deliberately doesn't include `pip`: its use is an implementation detail and it's possible we'll swap it for `uv` further down the line.
> Replace `pip-compile` command with `compile-reqs`

- airlock/templates/file_browser/group.html
- tests/functional/test_request_pages.py
- change button type for Delete Comment button from cancel to submit (fixes bug closing Context modal when there's a delete comment button as well as a Cancel button)
- only show Delete comment button in the template if the user_can_comment flag is also present. 
- Fix the "blinded" pill to remove duplicate text and only show it for comments in the current turn
> Delete comment visibility

- pyproject.toml
- tests/functional/utils.py
We only run the tests that generate the docs screenshots when we need them (and not by default with just test-all). Omit them from coverage so we don't get spurious coverage failures locally because of the skipped tests. There's nothing critical in these tests (or the helper functions that only they use) that we need to ensure coverage for.
> Omit docs screenshot tests from coverage

- airlock/business_logic.py
- airlock/permissions.py
- airlock/policies.py
- airlock/templates/file_browser/request/dir.html
- airlock/templates/file_browser/request/file.html
- airlock/templates/file_browser/request/request.html
- airlock/views/helpers.py
- airlock/views/request.py
- tests/factories.py
- tests/functional/test_docs_screenshots.py
- tests/functional/test_request_pages.py
- tests/integration/views/test_request.py
- tests/local_db/test_data_access.py
- tests/unit/test_business_logic.py
- tests/unit/test_permissions.py
The main aim of this PR was to move the logic about which buttons to show at the top of the request content (and whether to enable/disable them, show tooltips etc) out of the template and into the views.
We now build a `content_buttons` dict for each type of content that needs to display buttons (request, file, dir) and the template just needs to use that to determine whether to show buttons.
However, I also refactored the logic to make use of the permissions in permissions.py, and in doing so came across the odd permission that was only enforced at the view/template level, and the odd one that was missing - the main ones being:
- a user can't submit a review if there are no output files on the request (this was enforced in the view only, by disabling the submit-review button)
- a user …
> Template refactoring part 2 plus bonus permissions updates

- airlock/static/assets/file_browser/index.css
- airlock/static/assets/file_browser/tree.css
- airlock/templates/base.html
- airlock/templates/file_browser/_includes/file_content.html
- airlock/templates/file_browser/contents.html
- airlock/templates/file_browser/index.html
- airlock/templates/file_browser/request/dir.html
- airlock/templates/file_browser/workspace/dir.html
- assets/src/scripts/resizer.js
- tailwind.config.js
- vite.config.js
Closes #223 
To remove double scrollbars we have:
- Set up the page so that the min-height is the full size of the viewport
- When the file browser pages are opened, we set the height to the full size of the viewport, and remove the min-height
- When loading a file, the iframe height is determined by checking the height of the screen from the top of the `<iframe>`
- This height is calculated on page load, on HTMX content change, and on browser window resize
> Stop double scrollbars appearing when displaying content

- airlock/forms.py
- airlock/templates/_includes/header.html
- airlock/templates/activity.html
- airlock/templates/file_browser/file_content/csv.html
- airlock/templates/file_browser/request/filegroup.html
- airlock/templates/file_browser/request/request.html
Replace inline styles with Tailwind CSS classes.
This PR also tidies up the `airlock/templates/file_browser/request/filegroup.html` form, as it had many extraneous `<div />`'s that are not required.
> Remove inline styles

- airlock/renderers.py
- requirements.prod.in
- requirements.prod.txt
- tests/unit/test_renderers.py
Convert the text of the log file to HTML using ansi2html, which converts ANSI colour codes to css classes so we get the colour formatting from the original log.
It produces a full HTML file, which isn't what we want to display. We just extract the `<pre>` tag which contains the log content, and the `<style>` tag which contains the relevant inline css.
Before:
After:
> Add a renderer for log files that can render ansi colours

- airlock/templates/_components/datatable.html
- assets/src/scripts/datatable.js
- tests/functional/test_workspace_pages.py
Previously, our datatable `<table>` started out with a "hidden" class, which was removed when the datatable was initialised. This prevented the appearance of unformatted tables before the nicely formatted datatable was ready.
However, when a filter matches nothing and is then reset, simple datatables refreshes the original table element, which was reinstating its hidden attribute, so we ended up with a blank page.
We now wrap the table in another containing div, and apply the hidden class to that instead. It has the same effect in hiding the table until it's initialised, but isn't affected by the refresh after a removed unmatching filter.
Fixes #680
> Fix bug in CSV filtering

- .github/workflows/job-server.yml
- job-server/local-setup.sh
Also, remove the defunct slack notification on failure, which didn't
work, and has been superseeded by the workflows dashboard
> Update to create_user changes in job-server

- .github/workflows/update-dependencies.yml
This uses the new [update-dependencies-action](https://github.com/opensafely-core/update-dependencies-action).
Instead of the default GITHUB_TOKEN, it is using a token created by an installed app, `opensafely-core Create PR`,
which has the following repository permissions:
- contents: read and write
- pull-requests: read and write
This means it will trigger the usual workflows (checks/tests etc) that any other PR triggers.
[This PR](https://github.com/opensafely-core/airlock/pull/699) was created by this workflow (with a temporary commit that made it [run](https://github.com/opensafely-core/airlock/actions/runs/11440006463) on pushes to this branch)
> Add a workflow to update dependencies

- .github/dependabot.yml
- requirements.prod.in
- requirements.prod.txt
Replace dependabot for everything except GitHub Action updates.
Python dependencies are now updated by our [update-dependencies-action](https://github.com/opensafely-core/update-dependencies-action/)
Also upgrades opensafely-pipeline.
> Replace dependabot

- docs/index.md
The regular link checker in the OpenSAFELY documentation was complaining about this broken link.
> Fix broken link warning

- airlock/middleware.py
- requirements.prod.in
- requirements.prod.txt
- services/tracing.py
- tests/integration/test_middleware.py
- tests/integration/views/test_request.py
- tests/integration/views/test_workspace.py
- tests/test_tracing.py
- removes sqlite otel instrumentation (it's noisy and doesn't give us much that we care about)
- adds the user to the current span in the user middleware
- adds all the custom attributes that we add in the @instrument decorater to the parent span as well as the new span created in the decorator
There's more to add in a later PR for spans in specific views:
- adding workspace to request views
- adding useful counts etc (e.g. number of files added to request, number of files released)
> Otel updates

- airlock/business_logic.py
- old_api/__init__.py
- tests/integration/test_old_api.py
- tests/unit/test_business_logic.py
Note: depends on https://github.com/opensafely-core/job-server/pull/4810
Changes `old_api.create_release` to `old_api.get_or_create_release` to reflect the job-server change above.
Catches the "already uploaded" error from job-server on a re-release attempt, so a re-release will continue to upload files that failed before.
Fixes #742
> Handle re-releases and re-uploads

- docs/airlock-includes/glossary.md
- docs/explanation/why-airlock.md
- docs/explanation/workflow-and-permissions.md
- docs/explanation/workspace-vs-request-files.md
- docs/how-tos/access-airlock.md
- docs/how-tos/create-and-submit-a-release-request.md
- docs/how-tos/edit-file-on-request.md
- docs/how-tos/release-files.md
- docs/how-tos/respond-to-returned-request.md
- docs/how-tos/review-a-request.md
- docs/how-tos/view-workspace-files.md
- docs/how-tos/withdraw-request.md
- docs/index.md
- docs/reference/terms-and-definitions.md
- mkdocs.yml
Fixes [#1701](https://github.com/opensafely/documentation/issues/1701)
1) Make glossary entries more Airlock-specific
This will prevent the airlock glossary being triggered in the main
docs for commonly-used terms (e.g. "vote") used in a non-Airlock
context.
Plus some incidental typo fixes
2) Update navigation
Remove unused footer navigation - this is handled by the navigation
theme defined in mkdocs.yml.
Also updates some section titles (so that the navigation shows e.g.
"Reference" instead of "Index"
> Make glossary entries more Airlock-specific

- .github/workflows/update-dependencies.yml
- justfile
- scripts/upgrade-pipeline.sh
Because we don't publish it to pypi, we can't use the pip workflow
> Upgrade pipeline library automatically

- airlock/enums.py
- airlock/models.py
- airlock/templates/file_browser/request/request.html
- airlock/views/helpers.py
- airlock/views/request.py
- tests/functional/test_e2e.py
- tests/integration/views/test_request.py
- tests/unit/test_models.py
Fixes #771 
Change the displayed status for "Approved" in the status pills to "Approved - Files uploading"
(Note that I haven't changed it in the main request overview panel, which is consistent with how we dislay other statuses that have a custom label (i.e. partially reviewed/reviewed))
When the request is approved, but files are still uploading, the "Release files" button is disabled, and changes to "Re-release files" (as in screenshot above).
When all files have been attempted 3x, and some are still not uploaded, the "Re-release files" button is enabled so that the user can re-try the release. 
Tooltips when files are uploading (disabled re-release button):
And when uploads have tried and failed (enabled re-release button):
Note: tooltip placement is a bit wonky, but this is the case …
> Disable the release files button until all files have attempted to upload the max number of times

- airlock/models.py
- airlock/templates/file_browser/request/request.html
- tests/functional/test_request_pages.py
Fixes #773 
To give users visibility on the upload progress of their released requests, we now show the uploaded file count on the request overview page, with an icon to indicate status.
Released, all files uploaded:
Approved, upload in progress (release files button is disabled):
Approved, upload failed (release files button is enabled and release can be re-tried):
Note: haven't updated the docs yet, as I plan to do that next (#775)
> Show uploaded file count with icons on request overview page

- assets/src/scripts/datatable.js
- tests/functional/test_workspace_pages.py
In some situations the `buildTables()` method that wires up the `DataTables` was being called twice. In most situations it just causes a console error. But with some combinations of page refresh and using the back button it caused the table to not display. This fixes it by excluding any tables that have already been wired up.
> Fix bug where datatable was loading twice in some situations

- docs/how-tos/review-a-request.md
Also make it clearer how to navigate to the request overview page in order to click return/reject buttons.
Fixes #641 
When I reviewed the [user comment ](https://bennettoxford.slack.com/archives/C01UJLWNZJT/p1733908820639609)about this again, I realised that the thing that had caused confusion was not so much the review consolidation itself, but rather where to go to find the Return button after consolidation was done.  So I've adding some extra wording around the consolidation, but also added more explicit instructions on how to get to the request overview page, and linked to it from the return/reject sections. Releasing has its own how-to, with screenshots, so I think it's clear where the buttons are there.
> Add some addition review consolidation docs

- airlock/templates/_includes/header.html
To make it more obvious which dev user is currently logged in:
> Show current logged in dev user in nav bar

- .github/workflows/main.yml
- dotenv-sample
- tests/functional/test_docs_screenshots.py
- tests/functional/utils.py
They now only wirte the screenshots if you explicitly tell them to via env var, which we do in CI.
This helps catch things locally, and preserves the default effect of not churning screenshot files.
> Switch the screenshot tests to always run

- airlock/login_api.py
- airlock/middleware.py
- tests/conftest.py
- tests/factories.py
- tests/functional/test_docs_screenshots.py
- tests/functional/test_login.py
- tests/integration/test_auth_views.py
- tests/integration/test_middleware.py
This is in preparation for switching to a db user object.  Separating out last_refresh keeps things cleaner, making the user object purely a representation of the auth API data.
Includes fixture refactoring to make stubbing the auth api easier.
> Refactor login api and separate last_refresh from user data

- airlock/management/commands/run_file_uploader.py
- tests/integration/management/commands/test_run_file_uploader.py
The uploader was incorrectly uploading the workspace file content instead of the request file content. This fixes the bug and adds a test for it.
> Fix upload bug when file content has changed

- tests/functional/test_e2e.py
No idea if this will improve things, but I've seen the iframe timeout a few times in the past couple of days (only on CI), so maybe using playwright's iframe-specific things will be more reliable. 
(see #780)
> Use playwright's frame locators to assert iframe content

- tests/integration/management/commands/test_run_file_uploader.py
Use Mock.assert_called_with() instead of assert Mock.called_with() The latter is ok on python 3.11 but won't work in 3.12, and the former is the correct way to assert args a mock is called with.
> Fix a mock assert call

- DEVELOPERS.md
- docker/justfile
- dotenv-sample
- justfile
Add a mac version of `just get-chromium`.
Detects the OS and downloads the relevant version of chromium v108 for MacOS  or Linux, depending on the local OS.
A PLATFORM env var can be passed in to override this in `just docker/test` to use the linux version when running tests in docker on a Mac.
The executable path is different; I haven't tried to detect and set it for users, just added a warning if you're on MacOS and the `PLAYWRIGHT_BROWSER_EXECUTABLE_PATH` is set to the linux one.
> Chromium for mac

- airlock/login_api.py
- airlock/middleware.py
- tests/conftest.py
- tests/factories.py
- tests/functional/test_e2e.py
- tests/integration/test_middleware.py
- tests/integration/views/test_workspace.py
- tests/unit/test_login_api.py
This is more preparatory work for landing django.contrib.auth based users.
It fixes a series of small issues that the db work uncovered. I've have pulled them out into a bit of grab bag PR in order to keep the db PR as small as possible.
The main change is making login_api.py not responsible for managing dev users last_refresh to avoid dealing with refreshing these in the middleware. We now do refresh dev users, but they automatically succeed.
The were some extra bits of telemetry, and also some global test factory usage that won't work when the users are backed by a db, so fix those now.
> Separate last refresh

- airlock/static/assets/file_browser/tree.css
The cursor is now only a pointer in places you can click. So on folders, groups, filenames, expanders you get a finger pointer:
But on the dotted lines indicating folder structure you don't
The change works by restricting the `cursor:pointer` to anything that is a `folder-name` e.g. the request, groups and folders. The files retain their pointer as they are `a` hyperlinks which get the pointer from default browser styles.
> File browser pointer only in places you can click

- assets/src/styles/main.css
Group now looks like this:
instead of this:
> Group no longer looks like a hyperlink

- tests/functional/conftest.py
- tests/functional/test_e2e.py
- tests/functional/test_workspace_pages.py
Playwright docs warn that `wait_for_timeout` is flaky https://playwright.dev/python/docs/api/class-frame#frame-wait-for-timeout
Replace it with a wait for the htmx class that's added and then removed during an htmx operation.
https://htmx.org/docs/#request-operations
Also wait for htmx to be done in the `find_and_click` helper function. Not all of these clicks will involve htmx, but lots of them do. Note that we could wait for `htmx-added` counts of 1 and then 0, which would verify that an htmx swap happened - but it doesn't always pick up the 1 count, even when it's definitely an htmx operation, so I think sometimes it's too fast for playwright; in any case, this means that we can add it in the `find_and_click` function without being too bothered about whether it's htmx or not, we just …
> Replace wait_for_timeout with wait for htmx classes

- airlock/static/assets/file_browser/index.css
- airlock/templates/file_browser/request/file.html
- airlock/views/helpers.py
- airlock/views/request.py
Fixes #784 
Before submitting review (reset-review button is enabled):
After submitting review  (reset-review button is disabled, using same styling as other disabled buttons):
Also adds the "cursor-not-allowed" class to selected and disabled voting buttons so it shows the :no_entry_sign: when you hover over it, instead of a cursor (similar to other disabled buttons)
> Differentiate visibly between selected and disabled voting buttons

- airlock/templates/_components/header/request/header.html
- airlock/templates/file_browser/request/header.html
- airlock/views/request.py
- tests/functional/test_request_pages.py
- tests/integration/views/test_request.py
Fixes #718 
Fixes #797 
Include links back to the request overview page in the action required alerts (visible when a user completes their file reviews but hasn't submitted the review yet, or when a request is ready to return/reject/release). For the submit-review, i considered putting a link to actually submit the review in the alert, rather than directing the user back to the overview page, but it requires a form and a post, and would move more logic out to the templates.
Also adds the group into the header, because both of these elements are different if you're on the overview page, and use the same htmx oob to update when the user navigates around via tree links. 
Example overview page: No group in header, no links in alert
Example content page (a file, same header for group and …
> Better alerts for action required and group name in request header

- airlock/models.py
- tests/functional/test_request_pages.py
- tests/integration/views/test_request.py
Fixes #799 
Collaborators (i.e. users who are not the author but who have access to a workspace) can add comments to a request that is in pending or returned state. However, if they are also an output checker they can now only add comments that are public (i.e. they can only comment as a collaborator, not as an output-checker)
> Prevent output checkers from adding private comments for requests in author-owned states

- .github/workflows/trace-functional-tests.yml
- .gitignore
- DEVELOPERS.md
- tests/functional/test_e2e.py
This reworks some playwright locators, especially those around the flakiest bits (generally the tree clicks and iframe content), by using the locators that are identified in the [Playwright Inspector](https://playwright.dev/python/docs/running-tests#debugging-tests) when running the tests with `PWDEBUG=1`
Also adds a GHA workflow to run the functional tests with tracing and upload the trace as an artifact if the test fails.  The workflow will run every hour, so if it fails, we can download the trace for the failing test(s) and inspect the page state at the time of the failure. Hopefully this will give us some insights into how we might fix the flakiness.
The trace is found with the workflow run, [this is an example](https://github.com/opensafely-core/airlock/actions/runs/13544691316) from …
> Some more functional tests rework and a tracing workflow

- tests/functional/test_docs_screenshots.py
The test has failed a couple of times at [this point](https://github.com/opensafely-core/airlock/actions/runs/13559964118/job/37901163083#step:8:531) 
Looking at the trace replay, I suspect a conflict between the htmx polling for the uploaded files and the page.goto() call; tentatively suggesting that using page.reload() will help.
> Reload page in screenshot test

- tests/functional/test_docs_screenshots.py
The htmx polling is still going on at this point, so there's no need to reload the page, and possibly doing so is causing the occasional conflict (a "maybe frame was detached?" error on the page.reload() call). We just check that the header status has changed to RELEASED before taking the screenshot.
> Don't reload the page after changing status to released

- airlock/models.py
- tests/factories.py
- tests/integration/views/test_code.py
- tests/unit/test_models.py
This resulted in the code browser generating the wrong URLs in its file menu which meant that the initial load of the `project.yaml` file worked, but clicking any of the other filenames would silently fail (the HTMX call would 403 but no error would be displayed to the user).
In cases where the repo name happened to match the workspace name things would work fine, which is why we didn't spot this locally.
Closes #845
> Fix workspace name/repo name mixup

- airlock/business_logic.py
- airlock/management/commands/run_file_uploader.py
- airlock/models.py
- airlock/permissions.py
- airlock/templates/file_browser/request/filegroup.html
- airlock/views/request.py
- airlock/visibility.py
- local_db/data_access.py
- local_db/models.py
- tests/factories.py
- tests/integration/management/commands/test_run_file_uploader.py
- tests/integration/test_visibility.py
- tests/integration/views/test_request.py
- tests/local_db/test_data_access.py
- tests/unit/test_business_logic.py
- users/models.py
Basically, wherever we used a username string, we now have a db User object.
This is a consistent and more future-proof API, as it allows us natural access to full user data whenever we need it, moves us away from using username (which can change), and allows us to easily change the User model without altering the API again.
The local_db DAL implementation still just persists the user_id, however (which is currently just username, but we expect in future that it could be a different (e.g. Github) id, so we can support renames.
However, doing this when combined with our to_dict/from_dict serialisation barrier between the BLL and the DAL, creates a slightly strange interaction.  Everything in those dicts so far had been native python types, in part because it was kind of simulating a future …
> Switch from username string to User object in BLL/DAL

- airlock/middleware.py
- services/tracing.py
- tests/integration/test_middleware.py
- tests/integration/views/test_request.py
- tests/integration/views/test_workspace.py
This fixes a missed check in the services instrument to be user.is_authenticated, rather then user existing, as with django.contrib.auth, the user always exists.
Also, track the user_id and username separately, to match the code, and to be ready for when user_id changes.
Additionally, rather than have an emtpy string when there is no user, use the string "anonymous" as it is unambiguous when veiwing the telemetry, and matches the way django.auth.contrib works
> Update telemetry with new user details

- airlock/templates/_components/header/request/header.html
- airlock/templates/_components/user.html
- airlock/templates/_includes/header.html
- airlock/templates/activity.html
- airlock/templates/file_browser/request/filegroup.html
- airlock/templates/requests_for_output_checker.html
- airlock/templates/requests_for_researcher.html
- airlock/templates/requests_for_workspace.html
- airlock/templates/workspaces.html
- airlock/templatetags/airlock_components.py
- tests/factories.py
- tests/integration/views/test_request.py
- tests/local_db/test_data_access.py
- users/models.py
The username is available as title tooltip.
This is achevied by implementing new `airlock_user` component. It's very simple, but we may want to do more in future (e.g. link to an view for that user, or provided a better toolip).
Fixes #443 at last
> Use user fullnames on UI

- airlock/renderers.py
- airlock/templates/file_browser/file_content/csv.html
I gave up trying to figure out how to do the CSS the proper way and so just added a style element to the head.
Preview:
Closes #713
> Add row numbers and sticky headers to tables

- tests/factories.py
- tests/functional/conftest.py
- tests/functional/test_e2e.py
- tests/functional/test_workspace_pages.py
- tests/users/test_models.py
- users/models.py
A user's `fullname` in job-server can be an empty string, which is not ideal. This changes the fallback to username to trigger on both the absence of a `fullname` key *or* its value being Falsey, i.e. `""`
Partially related to #863
> Better fullname fallback

- tests/factories.py
This test previously gave an unhelpful error message about being unable to add a released file to the second request:
from airlock.enums import RequestStatus
from . import factories
def test_multiple_requests(mock_old_api):
author = factories.create_airlock_user(
username="author", workspaces=["test1"], output_checker=False
)
factories.create_request_at_status(
"test1",
author=author,
status=RequestStatus.APPROVED,
files=[factories.request_file(approved=True, path="file1.txt")],
)
factories.create_request_at_status(
"test1",
author=author,
status=RequestStatus.APPROVED,
files=[factories.request_file(approved=True, path="file2.txt")],
)
> Improve default contents for request_file factory

- airlock/templates/add_or_change_files.html
- assets/src/styles/main.css
Makes longer filenames look nicer in the modals
Before:
After:
> Make the add-or-change and update modals wider

- airlock/templates/_components/datatable.html
- airlock/templates/file_browser/file_content/csv.html
- assets/src/scripts/datatable.js
In particular for csv files.
- sometimes the css for the class `hidden` is loaded too late and you get a flash of the unstyled table before it has a chance to set the style `display:none`. So we do that with inline styles rather than classes. Also do this for things like the padding and the font of the loading message to avoid them suddenly shifting.
- sometimes the loading message doesn't immediately display when the file is loaded. I think it was because the datatable.js file was immediately being called before the html was loaded and so the UI paint was delayed by the datatable script. By moving this to the end of the file it allows the html to render before the script is called.
- also added a spinner to make it look nicer - though in the occasional situations when the css fails to …
> A few minor tidy ups to the "loading file" behaviour for large files

- airlock/views/request.py
- docs/how-tos/review-a-request.md
- tests/integration/views/test_request.py
* fixes #722 
* if all files are approved, show a new message with a warning. if any files are not approved, show the current message.
> Show a different confirmation message for returning an approved request

- airlock/templates/file_browser/index.html
- justfile
Looks like this:
[Screencast from 07-03-25 12:04:35.webm](https://github.com/user-attachments/assets/8ce8bbb5-6ec8-4fac-889e-e8f044f4c024)
> Make tree-view expand to display long file names and nested directories

- airlock/file_browser_api.py
- airlock/models.py
* we assert that both Workspaces and ReleaseRequests conform to the AirlockContainer protocol
* but these methods are only applicable to the specific types
* they return None if not applicable, but PathItem already has None as the default value for these attributes
> Remove dummy methods from AirlockContainer

- airlock/business_logic.py
- tests/unit/test_business_logic.py
Fixes #912 
The group was missing in audit events for resetting votes, which meant that it didn't show up in the group audit log along with approve/request changes votes.
> Include the group in reset-review audit events

- tests/functional/test_e2e.py
We're still getting some occasional failures on the iframe content in the functional tests. This just adds an additional expect() around the locator itself to try and figure out whether it's the locator itself that hasn't been found (i.e. the iframe container in the contents) or the loaded file content.
> Add some extra expects around the iframe locator in functional tests

- .gitignore
- requirements.dev.in
- requirements.dev.txt
- tests/functional/csv_generator.py
- tests/functional/test_csv_viewer.py
Currently to display a csv file in airlock we:
- read the file from disk
- parse it with `csv.reader()`
- render it to a HTML table via a Django template
- enhance the table with a client side javascript library
If there was a bug somewhere in this flow, then in theory you could have a csv file that displayed differently in airlock. This is an attempt to write tests to confirm that this will never happen.
> Add hypothesis tests to check that randomly generated csv files display correctly in airlock

- airlock/renderers.py
- airlock/views/helpers.py
- tests/integration/views/test_helpers.py
- tests/unit/test_renderers.py
Fixes a bug in the last modified time used*, and improves the template reloading in development
- Cache the template using its content only
File content is cached based on both the content source file and the template file. [Here](https://github.com/opensafely-core/airlock/blob/8fc9f5cf85ef5bd445812f23adb9094c58918ebe/airlock/views/helpers.py#L95) we first check if the ETag (based on both file content and template) has changed; if it has, we then check the last modified time. However, we only use the content file's update time as the last_modified time, which means that if the template was updated after the content file, its changes wouldn't be registered.
We don't want to use the template's last modified date, because on a redeploy, these dates will change, even if the template content …
> Improve template caching

- .vscode/launch.json
- airlock/renderers.py
- airlock/templates/file_browser/_includes/file_content.html
- airlock/templates/file_browser/file_content/csv.html
- assets/src/scripts/clusterize-datatable.js
- assets/src/scripts/csv-datatable.js
- justfile
- package-lock.json
- package.json
- tests/functional/csv_generator.py
- tests/functional/test_csv_viewer.py
- tests/functional/test_workspace_pages.py
- tests/unit/test_renderers.py
- vite.config.js
Currently we use the simple-datatables library to display csv files. Because this requires rendering the entire table it can become a bit laggy, particularly when sorting and searching (searching isn't too bad except as it's incremental as you type, but is not great when you clear the selection). The sort of files we display in output checking are likely to be pretty small. But even so, users have noticed the slowness, and so we recently added better visual indications that something was happening when the table was loading and sorting.
This draft PR is an attempt to display the csv files in a much more responsive way. It uses a library called clusterize.js which solves the rendering problem of large tables by only actually creating DOM nodes for a few hundred rows at a time and updating …
> Making the csv display a lot more responsive

- .gitignore
- airlock/settings.py
- tests/integration/test_settings.py
Django by default uses an in-memory database during tests. We can't set WAL mode on an in-memory database, so the functional tests that have htmx polling and also run the file uploader occasionally hit a "database table is locked" error when the polling tries to read at the same time as the file uploader writes. We can use a filesystem db instead by setting a test db name in the DATABASES settings.
> Use a filesystem db in tests

- airlock/settings.py
- requirements.prod.in
- requirements.prod.txt
It was added in e35d761 for use by collect-me-maybe.sh, which was removed in 6703851.
> Remove django-extensions from requirements

- .github/workflows/trace-functional-tests.yml
Functional tests have been running hourly and haven't failed in a few weeks. Reduce them to running just once overnight.
> Reduce functional test workflow to nightly

- requirements.dev.in
- requirements.dev.txt
Playwright tests have been intermittently failing and/or getting a django UserWarning that a template variable can't be resolved (usually path_item.contents_url, sometimes path_item.contents_plaintext_url) since [this PR](https://github.com/opensafely-core/airlock/pull/965/) was merged, which upgraded playwright from 1.52.0 to 1.53.0. Although there's nothing in the [release notes](https://playwright.dev/python/docs/release-notes#version-153) that would suggest it would have this effect, let's pin it to see if the errors/warnings stop happening.
> Pin playwright to v1.52.0

- services/tracing.py
This makes it easier to target airlock metrics in the backend
> Add top level otel attributes

- job-server/docker-compose.yml
We intend to upgrade to PostgreSQL 16 for job-server.
This change keeps the Airlock development setup in line with that change.
See opensafely-core/job-server#4739
> Use PostgreSQL 16 for job-server
